export function getCompletionItems(vscode: typeof import("vscode"), namespace = "raylib"): import("vscode").CompletionItem[] {
  type Entry = [name: string, detail: string, snippet?: string];
  const fns: Entry[] = [
    ["SetShapesTexture", "Sets the texture to be used for shapes."],
    ["GetShapesTexture", "Gets the current texture used for shapes."],
    ["GetShapesTextureRectangle", "Gets the source rectangle of the current shapes texture."],
    ["DrawPixel", "Draws a pixel at the specified position with the specified color."],
    ["DrawPixelV", "Draws a pixel at the specified position (Vector2) with the specified color."],
    ["DrawLineV", "Draws a line between two points (Vector2)."],
    ["DrawCircleV", "Draws a circle at the specified position (Vector2) with the specified radius and color."],
    ["DrawCircleLines", "Draws the outline of a circle at the specified position with the specified radius and color."],
    ["DrawCircleLinesV", "Draws the outline of a circle at the specified position (Vector2) with the specified radius and color."],
    ["DrawEllipseLines", "Draws the outline of an ellipse at the specified position with the specified radii and color."],
    ["DrawRectangleV", "Draws a rectangle at the specified position (Vector2) with the specified width, height, and color."],
    ["DrawRectangleRec", "Draws a rectangle using a Rectangle struct."],
    ["DrawRectanglePro", "Draws a rectangle with the specified position, size, and rotation."],
    ["DrawRectangleGradientH", "Draws a rectangle with a horizontal gradient."],
    ["DrawRectangleLinesEx", "Draws the outline of a rectangle with extended parameters."],
    ["DrawSplineLinear", "Draws a linear spline."],
    ["DrawSplineBasis", "Draws a basis spline."],
    ["DrawSplineCatmullRom", "Draws a Catmull-Rom spline."],
    ["DrawSplineBezierQuadratic", "Draws a quadratic Bezier spline."],
    ["DrawSplineBezierCubic", "Draws a cubic Bezier spline."],
    ["DrawSplineSegmentLinear", "Draws a segment of a linear spline between two points."],
    ["DrawSplineSegmentBasis", "Draws a segment of a basis spline."],
    ["DrawSplineSegmentCatmullRom", "Draws a segment of a Catmull-Rom spline."],
    ["DrawSplineSegmentBezierQuadratic", "Draws a segment of a quadratic Bezier spline."],
    ["DrawSplineSegmentBezierCubic", "Draws a segment of a cubic Bezier spline."],
    ["GetSplinePointLinear", "Gets a point on a linear spline."],
    ["GetSplinePointBasis", "Gets a point on a basis spline."],
    ["GetSplinePointCatmullRom", "Gets a point on a Catmull-Rom spline."],
    ["GetSplinePointBezierQuad", "Gets a point on a quadratic Bezier spline."],
    ["GetSplinePointBezierCubic", "Gets a point on a cubic Bezier spline."],
    ["CheckCollisionRecs", "Checks collision between two rectangles."],
    ["CheckCollisionCircles", "Checks collision between two circles."],
    ["CheckCollisionCircleRec", "Checks collision between a circle and a rectangle."],
    ["CheckCollisionCircleLine", "Checks collision between a circle and a line."],
    ["CheckCollisionPointRec", "Checks collision between a point and a rectangle."],
    ["CheckCollisionPointCircle", "Checks collision between a point and a circle."],
    ["CheckCollisionPointTriangle", "Checks collision between a point and a triangle."],
    ["CheckCollisionPointLine", "Checks collision between a point and a line."],
    ["CheckCollisionPointPoly", "Checks collision between a point and a polygon."],
    ["CheckCollisionLines", "Checks collision between two lines."],
    ["GetCollisionRec", "Gets the collision rectangle between two rectangles."],
    ["InitWindow", "Initializes a window with specified width, height, and title.", "raylib.InitWindow(${1:width}, ${2:height}, ${3:title})"],
    ["CloseWindow", "Closes the current window and releases all associated resources."],
    ["WindowShouldClose", "Checks if the window should close."],
    ["GetClipboardImage", "Retrieves an image from the system clipboard."],
    ["SetWindowIcon", "Sets the window icon using an image."],
    ["TakeScreenshot", "Captures a screenshot of the current window."],
    ["GetFPS", "Retrieves the current frames per second (FPS) of the application."],
    ["IsWindowMinimized", "Checks if the current window is minimized."],
    ["IsWindowMaximized", "Checks if the current window is maximized."],
    ["RestoreWindow", "Restores the window if it is minimized or maximized."],
    ["ToggleFullscreen", "Toggles fullscreen mode for the window."],
    ["SetClipboardText", "Sets the clipboard text to the specified value."],
    ["GetClipboardText", "Gets the text currently stored in the system clipboard."],
    ["GetMouseX", "Gets the X coordinate of the current mouse position."],
    ["GetMouseY", "Gets the Y coordinate of the current mouse position."],
    ["GetMousePosition", "Gets the current position of the mouse as a Vector2."],
    ["GetMouseWheelMove", "Gets the movement of the mouse wheel."],
    ["GetFrameTime", "Gets the frame time (time to process one frame) in seconds."],
    ["IsKeyReleased", "Checks if a specific key was released during the current frame."],
    ["GetMonitorWidth", "Gets the width of the specified monitor."],
    ["GetMonitorHeight", "Gets the height of the specified monitor."],
    ["MaximizeWindow", "Maximizes the application window."],
    ["MinimizeWindow", "Minimizes the application window."],
    ["SetWindowTitle", "Sets the title of the application window."],
    ["SetWindowPosition", "Sets the position of the application window."],
    ["SetWindowMonitor", "Sets the monitor on which the window is displayed."],
    ["SetWindowSize", "Sets the size of the application window."],
    ["SetConfigFlags", "Sets configuration flags for the application window."],
    ["GetScreenWidth", "Gets the width of the screen."],
    ["GetScreenHeight", "Gets the height of the screen."],
    ["GetMonitorCount", "Gets the number of connected monitors."],
    ["GetMonitorName", "Gets the name of a specific monitor."],
    ["GetMonitorPhysicalWidth", "Gets the physical width of a specific monitor in millimeters."],
    ["GetMonitorPhysicalHeight", "Gets the physical height of a specific monitor in millimeters."],
    ["GetMonitorRefreshRate", "Gets the refresh rate of a specific monitor."],
    ["GetMonitorPosition", "Gets the position of a specific monitor on the screen."],
    ["GetTime", "Gets the current time since the application started."],
    ["GetRandomValue", "Gets a random integer value between min and max (inclusive)."],
    ["SetTargetFPS", "Sets the target frames per second (FPS) for the application."],
    ["GetTargetFPS", "Gets the currently set target frames per second (FPS)."],
    ["IsKeyDown", "Checks if a specific key is currently being held down."],
    ["IsKeyUp", "Checks if a specific key is currently not being held down."],
    ["IsMouseButtonDown", "Checks if a specific mouse button is currently being held down."],
    ["IsMouseButtonUp", "Checks if a specific mouse button is currently up (not pressed)."],
    ["SetMousePosition", "Sets the mouse position on the screen."],
    ["SetMouseOffset", "Sets the mouse offset relative to the window."],
    ["SetMouseScale", "Sets the scale for mouse input."],
    ["GetTouchPosition", "Gets the position of a touch input."],
    ["ShowCursor", "Shows the mouse cursor on the screen."],
    ["HideCursor", "Hides the mouse cursor on the screen."],
    ["IsCursorHidden", "Checks if the cursor is currently hidden."],
    ["EnableCursor", "Enables the mouse cursor."],
    ["DisableCursor", "Disables the mouse cursor."],
    ["GetClipboardTextLength", "Gets the length of the clipboard text."],
    ["IsWindowReady", "Checks if the window is ready."],
    ["IsWindowFocused", "Checks if the window is currently focused."],
    ["IsWindowFullscreen", "Checks if the window is in fullscreen mode."],
    ["IsWindowHidden", "Checks if the window is currently hidden."],
    ["IsWindowResized", "Checks if the window has been resized."],
    ["IsWindowState", "Checks if the window has a specific state."],
    ["SetWindowState", "Sets a specific state for the window."],
    ["ClearWindowState", "Clears a specific state for the window."],
    ["ToggleBorderlessWindowed", "Toggles borderless windowed mode."],
    ["SetWindowMinSize", "Sets the minimum size of the window."],
    ["SetWindowMaxSize", "Sets the maximum size of the window."],
    ["SetWindowOpacity", "Sets the opacity of the window."],
    ["SetWindowFocused", "Sets the window as focused."],
    ["GetWindowHandle", "Gets the window handle."],
    ["GetCurrentMonitor", "Gets the current monitor."],
    ["GetWindowScaleDPI", "Gets the window's DPI scale."],
    ["EnableEventWaiting", "Enables event waiting."],
    ["DisableEventWaiting", "Disables event waiting."],
    ["IsCursorOnScreen", "Checks if the cursor is on the screen."],
    ["BeginDrawing", "Starts a new frame for drawing on the screen."],
    ["EndDrawing", "Ends the current frame and presents the drawn content to the screen."],
    ["ClearBackground", "Clears the entire screen with the specified color."],
    ["DrawRectangle", "Draws a color-filled rectangle on the screen.", "raylib.DrawRectangle(${1:posX}, ${2:posY}, ${3:width}, ${4:height}, ${5:color})"],
    ["DrawCircle", "Draws a color-filled circle on the screen.", "raylib.DrawCircle(${1:centerX}, ${2:centerY}, ${3:radius}, ${4:color})"],
    ["DrawLineEx", "Draws a thick line with customizable start and end points.", "raylib.DrawLineEx(${1:startX}, ${2:startY}, ${3:endX}, ${4:endY}, ${5:thickness}, ${6:color})"],
    ["DrawEllipse", "Draws a color-filled ellipse on the screen.", "raylib.DrawEllipse(${1:centerX}, ${2:centerY}, ${3:radiusH}, ${4:radiusV}, ${5:color})"],
    ["DrawRectangleLines", "Draws the outline of a rectangle with specified parameters.", "raylib.DrawRectangleLines(${1:posX}, ${2:posY}, ${3:width}, ${4:height}, ${5:color})"],
    ["DrawRectangleGradient", "Draws a rectangle with a gradient fill.", "raylib.DrawRectangleGradient(${1:posX}, ${2:posY}, ${3:width}, ${4:height}, ${5:color1}, ${6:color2})"],
    ["DrawRectangleRounded", "Draws a rounded rectangle with specified parameters.", "raylib.DrawRectangleRounded(${1:posX}, ${2:posY}, ${3:width}, ${4:height}, ${5:roundness}, ${6:segments}, ${7:color})"],
    ["DrawLineStrip", "Draws a line strip with specified parameters.", "raylib.DrawLineStrip(${1:points}, ${2:color})"],
    ["DrawPoly", "Draws a polygon with specified parameters.", "raylib.DrawPoly(${1:center}, ${2:sides}, ${3:radius}, ${4:rotation}, ${5:color})"],
    ["DrawPolyLines", "Draws the outline of a polygon with specified parameters.", "raylib.DrawPolyLines(${1:center}, ${2:sides}, ${3:radius}, ${4:rotation}, ${5:color})"],
    ["DrawPolyLinesEx", "Draws the outline of a polygon with extended parameters.", "raylib.DrawPolyLinesEx(${1:center}, ${2:sides}, ${3:radius}, ${4:rotation}, ${5:thickness}, ${6:color})"],
    ["DrawCircleSector", "Draws a sector of a circle with specified parameters.", "raylib.DrawCircleSector(${1:center}, ${2:radius}, ${3:startAngle}, ${4:endAngle}, ${5:segments}, ${6:color})"],
    ["DrawCircleSectorLines", "Draws the outline of a sector of a circle with specified parameters.", "raylib.DrawCircleSectorLines(${1:center}, ${2:radius}, ${3:startAngle}, ${4:endAngle}, ${5:segments}, ${6:color})"],
    ["DrawRectangleGradientV", "Draws a rectangle with a vertical gradient fill.", "raylib.DrawRectangleGradientV(${1:posX}, ${2:posY}, ${3:width}, ${4:height}, ${5:top}, ${6:bottom})"],
    ["DrawRectangleGradientEx", "Draws a rectangle with an extended gradient fill.", "raylib.DrawRectangleGradientEx(${1:rec}, ${2:topLeft}, ${3:topRight}, ${4:bottomLeft}, ${5:bottomRight})"],
    ["DrawCircleGradient", "Draws a circle with a gradient fill.", "raylib.DrawCircleGradient(${1:centerX}, ${2:centerY}, ${3:radius}, ${4:innerColor}, ${5:outerColor})"],
    ["DrawLine", "Draws a line between two points.", "raylib.DrawLine(${1:startX}, ${2:startY}, ${3:endX}, ${4:endY}, ${5:color})"],
    ["DrawLineBezier", "Draws a Bezier line with specified parameters.", "raylib.DrawLineBezier(${1:startPos}, ${2:endPos}, ${3:thick}, ${4:color})"],
    ["DrawTriangle", "Draws a triangle with specified parameters.", "raylib.DrawTriangle(${1:v1}, ${2:v2}, ${3:v3}, ${4:color})"],
    ["DrawTriangleLines", "Draws the outline of a triangle with specified parameters.", "raylib.DrawTriangleLines(${1:v1}, ${2:v2}, ${3:v3}, ${4:color})"],
    ["DrawTriangleStrip", "Draws a strip of connected triangles using a list of vertices.", "raylib.DrawTriangleStrip(${1:points}, ${2:color})"],
    ["DrawRing", "Draws a ring with specified parameters.", "raylib.DrawRing(${1:center}, ${2:innerRadius}, ${3:outerRadius}, ${4:startAngle}, ${5:endAngle}, ${6:segments}, ${7:color})"],
    ["DrawRingLines", "Draws the outline of a ring with specified parameters.", "raylib.DrawRingLines(${1:center}, ${2:innerRadius}, ${3:outerRadius}, ${4:startAngle}, ${5:endAngle}, ${6:segments}, ${7:color})"],
    ["LoadSound", "Loads a sound from a file into memory.", "raylib.LoadSound(${1:fileName})"],
    ["PlaySound", "Plays a loaded sound.", "raylib.PlaySound(${1:sound})"],
    ["StopSound", "Stops a currently playing sound.", "raylib.StopSound(${1:sound})"],
    ["UnloadSound", "Unloads a loaded sound from memory.", "raylib.UnloadSound(${1:sound})"],
    ["LoadMusicStream", "Loads a music stream from a file into memory.", "raylib.LoadMusicStream(${1:fileName})"],
    ["PlayMusicStream", "Plays a loaded music stream.", "raylib.PlayMusicStream(${1:music})"],
    ["StopMusicStream", "Stops a currently playing music stream.", "raylib.StopMusicStream(${1:music})"],
    ["UpdateMusicStream", "Updates the buffers for a music stream.", "raylib.UpdateMusicStream(${1:music})"],
    ["SetMusicVolume", "Sets the volume for a music stream.", "raylib.SetMusicVolume(${1:music}, ${2:volume})"],
    ["SetSoundVolume", "Sets the volume for a sound.", "raylib.SetSoundVolume(${1:sound}, ${2:volume})"],
    ["IsSoundPlaying", "Checks if a sound is currently playing.", "raylib.IsSoundPlaying(${1:sound})"],
    ["InitAudioDevice", "Initializes the audio device."],
    ["CloseAudioDevice", "Closes the audio device."],
    ["IsAudioDeviceReady", "Checks if the audio device is ready."],
    ["SetMasterVolume", "Sets the master volume for all audio.", "raylib.SetMasterVolume(${1:volume})"],
    ["GetMasterVolume", "Gets the master volume for all audio."],
    ["IsWaveValid", "Checks if a wave is valid.", "raylib.IsWaveValid(${1:wave})"],
    ["LoadSoundFromWave", "Loads a sound from a wave.", "raylib.LoadSoundFromWave(${1:wave})"],
    ["LoadWave", "Loads a wave from a file.", "raylib.LoadWave(${1:fileName})"],
    ["LoadWaveFromMemory", "Loads a wave from memory.", "raylib.LoadWaveFromMemory(${1:fileType}, ${2:fileData}, ${3:dataSize})"],
    ["LoadSoundAlias", "Loads a sound alias.", "raylib.LoadSoundAlias(${1:alias}, ${2:fileName})"],
    ["IsSoundValid", "Checks if a sound is valid.", "raylib.IsSoundValid(${1:sound})"],
    ["UpdateSound", "Updates a sound buffer with new data.", "raylib.UpdateSound(${1:sound}, ${2:data}, ${3:dataSize})"],
    ["UnloadWave", "Unloads a wave from memory.", "raylib.UnloadWave(${1:wave})"],
    ["UnloadSoundAlias", "Unloads a sound alias from memory.", "raylib.UnloadSoundAlias(${1:alias})"],
    ["ExportWave", "Exports a wave to a file.", "raylib.ExportWave(${1:wave}, ${2:fileName})"],
    ["ExportWaveAsCode", "Exports a wave as C code.", "raylib.ExportWaveAsCode(${1:wave}, ${2:fileName})"],
    ["WaveCopy", "Copies a wave.", "raylib.WaveCopy(${1:wave})"],
    ["WaveCrop", "Crops a wave.", "raylib.WaveCrop(${1:wave}, ${2:initSample}, ${3:finalSample})"],
    ["WaveFormat", "Formats a wave.", "raylib.WaveFormat(${1:wave}, ${2:sampleRate}, ${3:sampleSize}, ${4:channels})"],
    ["LoadWaveSamples", "Loads wave samples.", "raylib.LoadWaveSamples(${1:wave})"],
    ["UnloadWaveSamples", "Unloads wave samples from memory.", "raylib.UnloadWaveSamples(${1:samples})"],
    ["IsMusicValid", "Checks if a music object is valid.", "raylib.IsMusicValid(${1:music})"],
    ["UnloadMusicStream", "Unloads a music stream from memory.", "raylib.UnloadMusicStream(${1:music})"],
    ["IsMusicStreamPlaying", "Checks if a music stream is currently playing.", "raylib.IsMusicStreamPlaying(${1:music})"],
    ["PauseMusicStream", "Pauses the currently playing music stream.", "raylib.PauseMusicStream(${1:music})"],
    ["ResumeMusicStream", "Resumes the paused music stream.", "raylib.ResumeMusicStream(${1:music})"],
    ["SeekMusicStream", "Seeks to a specific position in the music stream.", "raylib.SeekMusicStream(${1:music}, ${2:position})"],
    ["SetMusicPitch", "Sets the pitch for the music stream.", "raylib.SetMusicPitch(${1:music}, ${2:pitch})"],
    ["SetMusicPan", "Sets the pan for the music stream.", "raylib.SetMusicPan(${1:music}, ${2:pan})"],
    ["GetMusicTimeLength", "Gets the total length of the music stream.", "raylib.GetMusicTimeLength(${1:music})"],
    ["GetMusicTimePlayed", "Gets the total time played of the music stream.", "raylib.GetMusicTimePlayed(${1:music})"],
    ["LoadAudioStream", "Loads an audio stream with specified sample rate, sample size, and channel count.", "raylib.LoadAudioStream(${1:sampleRate}, ${2:sampleSize}, ${3:channels})"],
    ["IsAudioStreamValid", "Checks if an audio stream is valid.", "raylib.IsAudioStreamValid(${1:stream})"],
    ["UnloadAudioStream", "Unloads an audio stream from memory, freeing all associated resources.", "raylib.UnloadAudioStream(${1:stream})"],
    ["UpdateAudioStream", "Updates an audio stream with new audio data.", "raylib.UpdateAudioStream(${1:stream}, ${2:data}, ${3:frameCount})"],
    ["IsAudioStreamProcessed", "Checks if an audio stream is currently being processed.", "raylib.IsAudioStreamProcessed(${1:stream})"],
    ["PlayAudioStream", "Plays an audio stream, starting from the current buffer position.", "raylib.PlayAudioStream(${1:stream})"],
    ["PauseAudioStream", "Pauses the currently playing audio stream.", "raylib.PauseAudioStream(${1:stream})"],
    ["ResumeAudioStream", "Resumes a paused audio stream, continuing playback from its current position.", "raylib.ResumeAudioStream(${1:stream})"],
    ["IsAudioStreamPlaying", "Checks if an audio stream is currently playing.", "raylib.IsAudioStreamPlaying(${1:stream})"],
    ["StopAudioStream", "Stops the currently playing audio stream and resets its playback position.", "raylib.StopAudioStream(${1:stream})"],
    ["SetAudioStreamVolume", "Sets the volume for an audio stream.", "raylib.SetAudioStreamVolume(${1:stream}, ${2:volume})"],
    ["SetAudioStreamPitch", "Sets the pitch for an audio stream.", "raylib.SetAudioStreamPitch(${1:stream}, ${2:pitch})"],
    ["SetAudioStreamPan", "Sets the pan for an audio stream.", "raylib.SetAudioStreamPan(${1:stream}, ${2:pan})"],
    ["SetAudioStreamBufferSizeDefault", "Sets the default buffer size for an audio stream.", "raylib.SetAudioStreamBufferSizeDefault(${1:bufferSize})"],
    ["SetAudioStreamCallback", "Sets a callback function for an audio stream.", "raylib.SetAudioStreamCallback(${1:stream}, ${2:callback})"],
    ["AttachAudioStreamProcessor", "Attaches a processor to an audio stream.", "raylib.AttachAudioStreamProcessor(${1:stream}, ${2:processor})"],
    ["DetachAudioStreamProcessor", "Detaches a processor from an audio stream.", "raylib.DetachAudioStreamProcessor(${1:stream}, ${2:processor})"],
    ["AttachAudioMixedProcessor", "Attaches a processor to the mixed audio.", "raylib.AttachAudioMixedProcessor(${1:processor})"],
    ["DetachAudioMixedProcessor", "Detaches a processor from the mixed audio.", "raylib.DetachAudioMixedProcessor(${1:processor})"],
    ["GetFontDefault", "Gets the default font."],
    ["LoadFont", "Loads a font from a file."],
    ["LoadFontEx", "Loads a font from a file with extended parameters."],
    ["LoadFontFromImage", "Loads a font from an image."],
    ["LoadFontFromMemory", "Loads a font from memory."],
    ["IsFontValid", "Checks if a font is valid."],
    ["UnloadFont", "Unloads a font from memory."],
    ["ExportFontAsCode", "Exports a font as C code."],
    ["DrawFPS", "Draws the current FPS on the screen."],
    ["DrawText", "Draws text on the screen."],
    ["DrawTextEx", "Draws text on the screen with extended parameters."],
    ["DrawTextPro", "Draws text on the screen with additional options."],
    ["DrawTextCodepoint", "Draws a single codepoint as text on the screen."],
    ["DrawTextCodepoints", "Draws multiple codepoints as text on the screen."],
    ["SetTextLineSpacing", "Sets the line spacing for text."],
    ["MeasureText", "Measures the width of the text."],
    ["MeasureTextEx", "Measures the size of the text with extended parameters."],
    ["GetGlyphIndex", "Gets the index of a glyph in the font."],
    ["GetGlyphInfo", "Gets information about a glyph in the font."],
    ["GetGlyphAtlasRec", "Gets the atlas rectangle of a glyph in the font."],
    ["LoadUTF8", "Loads a UTF-8 string."],
    ["UnloadUTF8", "Unloads a UTF-8 string from memory."],
    ["LoadCodepoints", "Loads codepoints from a UTF-8 string."],
    ["UnloadCodepoints", "Unloads codepoints from memory."],
    ["GetCodepointCount", "Gets the count of codepoints in a UTF-8 string."],
    ["GetCodepoint", "Gets a codepoint from a UTF-8 string."],
    ["GetCodepointNext", "Gets the next codepoint in a UTF-8 string."],
    ["GetCodepointPrevious", "Gets the previous codepoint in a UTF-8 string."],
    ["CodepointToUTF8", "Converts a codepoint to a UTF-8 string."],
    ["TextCopy", "Copies text from one string to another."],
    ["TextIsEqual", "Checks if two strings are equal."],
    ["TextLength", "Gets the length of a text string."],
    ["TextFormat", "Formats a text string."],
    ["TextSubtext", "Gets a subtext from a text string."],
    ["TextReplace", "Replaces text in a string."],
    ["TextInsert", "Inserts text into a string."],
    ["TextJoin", "Joins text strings."],
    ["TextSplit", "Splits a text string."],
    ["TextAppend", "Appends text to a string."],
    ["TextFindIndex", "Finds the index of a substring in a text string."],
    ["TextToUpper", "Converts a text string to uppercase."],
    ["TextToLower", "Converts a text string to lowercase."],
    ["TextToPascal", "Converts a text string to Pascal case."],
    ["TextToSnake", "Converts a text string to snake case."],
    ["TextToCamel", "Converts a text string to camel case."],
    ["TextToInteger", "Converts a text string to an integer."],
    ["TextToFloat", "Converts a text string to a float."],
    ["LoadImage", "Loads an image from a file."],
    ["UnloadImage", "Unloads an image from memory."],
    ["LoadTexture", "Loads a texture from a file."],
    ["LoadTextureFromImage", "Loads a texture from an existing image."],
    ["UnloadTexture", "Unloads a texture from GPU memory."],
    ["UpdateTexture", "Updates the contents of a texture with new data."],
    ["GenTextureMipmaps", "Generates mipmaps for a texture."],
    ["ImageResize", "Resizes an image to the specified dimensions."],
    ["ImageFlipHorizontal", "Flips an image horizontally."],
    ["ImageFlipVertical", "Flips an image vertically."],
    ["ImageCopy", "Creates a copy of an image."],
    ["ImageCrop", "Crops an image to the specified rectangle."],
    ["ImageColorTint", "Tints an image with a specified color."],
    ["ImageColorInvert", "Inverts the colors of an image."],
    ["ImageColorGrayscale", "Converts an image to grayscale."],
    ["ImageColorBrightness", "Adjusts the brightness of an image."],
    ["ImageColorContrast", "Adjusts the contrast of an image."],
    ["ImageColorReplace", "Replaces a color in an image with another color."],
    ["LoadTextureCubemap", "Loads a cubemap texture from an image."],
    ["UpdateTextureRec", "Updates a specific region of a texture with new data."],
    ["LoadImageRaw", "Loads an image from raw pixel data."],
    ["LoadImageAnim", "Loads an animated image (GIF) from a file."],
    ["LoadImageAnimFromMemory", "Loads an animated image (GIF) from memory."],
    ["LoadImageFromMemory", "Loads an image from memory data."],
    ["LoadImageFromTexture", "Loads an image from a texture."],
    ["LoadImageFromScreen", "Loads an image from the current screen content."],
    ["IsImageValid", "Checks if an image is valid."],
    ["ExportImage", "Exports an image to a file."],
    ["ExportImageToMemory", "Exports an image to memory."],
    ["ExportImageAsCode", "Exports an image as source code."],
    ["GenImageColor", "Generates an image filled with a specific color."],
    ["GenImageGradientLinear", "Generates a linear gradient image."],
    ["GenImageGradientRadial", "Generates a radial gradient image."],
    ["GenImageGradientSquare", "Generates a square gradient image."],
    ["GenImageChecked", "Generates an image with a checkered pattern."],
    ["GenImageWhiteNoise", "Generates an image with white noise."],
    ["GenImagePerlinNoise", "Generates an image with Perlin noise."],
    ["GenImageCellular", "Generates an image with a cellular pattern."],
    ["GenImageText", "Generates an image with text."],
    ["ImageFromImage", "Extracts a sub-image from an existing image."],
    ["ImageFromChannel", "Extracts a specific color channel from an image."],
    ["ImageText", "Generates an image with a text string."],
    ["ImageTextEx", "Generates an image with extended text options."],
    ["ImageFormat", "Converts the format of an image."],
    ["ImageToPOT", "Converts an image to power-of-two dimensions."],
    ["ImageAlphaCrop", "Crops the image by removing transparent pixels around it."],
    ["ImageAlphaClear", "Clears alpha values from an image."],
    ["ImageAlphaMask", "Applies an alpha mask to an image."],
    ["ImageAlphaPremultiply", "Premultiplies the alpha channel of an image."],
    ["ImageBlurGaussian", "Applies a Gaussian blur to an image."],
    ["ImageKernelConvolution", "Applies a kernel convolution to an image."],
    ["ImageResizeNN", "Resizes an image using nearest-neighbor scaling."],
    ["ImageResizeCanvas", "Resizes the image canvas while maintaining the image's position."],
    ["ImageMipmaps", "Generates mipmaps for the image."],
    ["ImageDither", "Applies a dithering effect to the image."],
    ["ImageRotate", "Rotates the image by a specified angle."],
    ["ImageRotateCW", "Rotates the image 90 degrees clockwise."],
    ["ImageRotateCCW", "Rotates the image 90 degrees counterclockwise."],
    ["LoadImageColors", "Loads the color data from an image."],
    ["LoadImagePalette", "Loads the palette from an image."],
    ["UnloadImageColors", "Unloads the color data from memory."],
    ["UnloadImagePalette", "Unloads the image palette from memory."],
    ["GetImageAlphaBorder", "Gets the alpha border rectangle of an image."],
    ["GetImageColor", "Gets the color of a specific pixel in an image."],
    ["ImageClearBackground", "Clears the background of an image with a specified color."],
    ["ImageDrawPixel", "Draws a pixel at the specified position in an image."],
    ["ImageDrawPixelV", "Draws a pixel at the specified position (Vector2) in an image."],
    ["ImageDrawLine", "Draws a line between two points in an image."],
    ["ImageDrawLineV", "Draws a line between two points (Vector2) in an image."],
    ["ImageDrawLineEx", "Draws a line between two points with extended parameters in an image."],
    ["ImageDrawCircle", "Draws a circle in an image at a specified position."],
    ["ImageDrawCircleV", "Draws a circle in an image at a specified position (Vector2)."],
    ["ImageDrawCircleLines", "Draws the outline of a circle in an image at a specified position."],
    ["ImageDrawCircleLinesV", "Draws the outline of a circle in an image at a specified position (Vector2)."],
    ["ImageDrawRectangle", "Draws a rectangle in an image at a specified position."],
    ["ImageDrawRectangleV", "Draws a rectangle in an image at a specified position (Vector2)."],
    ["ImageDrawRectangleRec", "Draws a rectangle in an image using a Rectangle structure."],
    ["ImageDrawRectangleLines", "Draws the outline of a rectangle in an image."],
    ["ImageDrawTriangle", "Draws a triangle in an image using three points."],
    ["ImageDrawTriangleEx", "Draws a triangle in an image using extended parameters."],
    ["ImageDrawTriangleLines", "Draws the outline of a triangle in an image."],
    ["ImageDrawTriangleFan", "Draws a triangle fan in an image."],
    ["ImageDrawTriangleStrip", "Draws a triangle strip in an image."],
    ["ImageDraw", "Draws an image onto another image."],
    ["ImageDrawText", "Draws text on an image."],
    ["ImageDrawTextEx", "Draws text on an image using extended parameters."],
    ["LoadRenderTexture", "Loads a render texture."],
    ["IsTextureValid", "Checks if a texture is valid."],
    ["IsRenderTextureValid", "Checks if a render texture is valid."],
    ["UnloadRenderTexture", "Unloads a render texture from memory."],
    ["SetTextureFilter", "Sets the filter mode for a texture."],
    ["SetTextureWrap", "Sets the wrap mode for a texture."],
    ["DrawTexture", "Draws a texture at a specified position."],
    ["DrawTextureV", "Draws a texture at a specified position using a Vector2."],
    ["DrawTextureEx", "Draws a texture with extended parameters."],
    ["DrawTextureRec", "Draws a part of a texture."],
    ["DrawTexturePro", "Draws a texture with extended parameters."],
    ["DrawTextureNPatch", "Draws a texture using N-patch information."],
    ["ColorIsEqual", "Checks if two colors are equal."],
    ["Fade", "Applies fade effect to a color."],
    ["ColorToInt", "Converts a Color to an integer representation."],
    ["ColorNormalize", "Normalizes a Color to a Vector4."],
    ["ColorFromNormalized", "Converts a normalized Vector4 to a Color."],
    ["ColorToHSV", "Converts a Color to HSV."],
    ["ColorFromHSV", "Converts HSV (Hue, Saturation, Value) to a Color."],
    ["ColorTint", "Tints a Color with another Color."],
    ["ColorBrightness", "Adjusts the brightness of a Color."],
    ["ColorContrast", "Adjusts the contrast of a Color."],
    ["ColorAlpha", "Adjusts the alpha (transparency) of a Color."],
    ["ColorAlphaBlend", "Blends two Colors based on alpha blending."],
    ["ColorLerp", "Linearly interpolates between two Colors."],
    ["GetColor", "Gets the integer representation of a Color."],
    ["GetPixelColor", "Gets the color of a pixel from the screen at a given position."],
    ["SetPixelColor", "Sets the color of a specific pixel on the screen or render target."],
    ["GetPixelDataSize", "Gets the size of the pixel data in memory for an image or texture."],
    ["LoadModel", "Loads a model from a file."],
    ["DrawModel", "Draws a model with default parameters."],
    ["DrawModelEx", "Draws a model with extended parameters."],
    ["UnloadModel", "Unloads a model from memory."],
    ["UpdateModelAnimation", "Updates a model animation."],
    ["DrawMesh", "Draws a mesh with default parameters."],
    ["UnloadMesh", "Unloads a mesh from memory."],
    ["GenMeshCube", "Generates a cube mesh."],
    ["GenMeshSphere", "Generates a sphere mesh."],
    ["GenMeshPlane", "Generates a plane mesh."],
    ["DrawLine3D", "Draws a 3D line with specified parameters."],
    ["DrawPoint3D", "Draws a 3D point with specified parameters."],
    ["DrawCircle3D", "Draws a 3D circle with specified parameters."],
    ["DrawTriangle3D", "Draws a 3D triangle with specified parameters."],
    ["DrawTriangleStrip3D", "Draws a 3D triangle strip with specified parameters."],
    ["DrawCube", "Draws a 3D cube with specified parameters."],
    ["DrawCubeV", "Draws a 3D cube with specified parameters using a Vector3."],
    ["DrawCubeWires", "Draws the wireframe of a cube with specified parameters."],
    ["DrawCubeWiresV", "Draws the wireframe of a cube with specified parameters using a Vector3."],
    ["DrawSphereWires", "Draws the wireframe of a sphere with specified parameters."],
    ["DrawCylinder", "Draws a cylinder with specified parameters."],
    ["DrawCylinderEx", "Draws a cylinder with extended parameters."],
    ["DrawCylinderWires", "Draws the wireframe of a cylinder with specified parameters."],
    ["DrawCylinderWiresEx", "Draws the wireframe of a cylinder with extended parameters."],
    ["DrawCapsule", "Draws a capsule with specified parameters."],
    ["DrawCapsuleWires", "Draws the wireframe of a capsule with specified parameters."],
    ["DrawPlane", "Draws a plane with specified parameters."],
    ["DrawRay", "Draws a ray with specified parameters."],
    ["DrawGrid", "Draws a grid with specified parameters."],
    ["LoadModelFromMesh", "Loads a model from a mesh."],
    ["IsModelValid", "Checks if a model is valid."],
    ["GetModelBoundingBox", "Gets the bounding box of a model."],
    ["DrawBoundingBox", "Draws a bounding box with specified parameters."],
    ["DrawBillboard", "Draws a billboard with specified parameters."],
    ["DrawBillboardRec", "Draws a billboard with a specified rectangle."],
    ["DrawBillboardPro", "Draws a billboard with extended parameters."],
    ["UploadMesh", "Uploads a mesh to the GPU."],
    ["UpdateMeshBuffer", "Updates a mesh buffer with new data."],
    ["GetMeshBoundingBox", "Gets the bounding box of a mesh."],
    ["GenMeshTangents", "Generates tangents for a mesh."],
    ["ExportMesh", "Exports a mesh to a file."],
    ["ExportMeshAsCode", "Exports a mesh as C code."],
    ["GenMeshPoly", "Generates a polygon mesh."],
    ["GenMeshHemiSphere", "Generates a hemisphere mesh."],
    ["GenMeshCylinder", "Generates a cylinder mesh."],
    ["GenMeshCone", "Generates a cone mesh."],
    ["GenMeshTorus", "Generates a torus mesh."],
    ["GenMeshKnot", "Generates a knot mesh."],
    ["GenMeshHeightmap", "Generates a heightmap mesh."],
    ["GenMeshCubicmap", "Generates a cubicmap mesh."],
    ["LoadMaterials", "Loads materials from a file."],
    ["LoadMaterialDefault", "Loads the default material."],
    ["IsMaterialValid", "Checks if a material is valid."],
    ["UnloadMaterial", "Unloads a material from memory."],
    ["SetMaterialTexture", "Sets a texture for a material."],
    ["SetModelMeshMaterial", "Sets the material for a model mesh."],
    ["LoadModelAnimations", "Loads model animations from a file."],
    ["UnloadModelAnimation", "Unloads a model animation from memory."],
    ["UnloadModelAnimations", "Unloads model animations from memory."],
    ["IsModelAnimationValid", "Checks if a model animation is valid."],
    ["CheckCollisionSpheres", "Checks collision between two spheres."],
    ["CheckCollisionBoxes", "Checks collision between two boxes."],
    ["CheckCollisionBoxSphere", "Checks collision between a box and a sphere."],
    ["GetRayCollisionSphere", "Gets the collision information between a ray and a sphere."],
    ["GetRayCollisionBox", "Gets the collision information between a ray and a box."],
    ["GetRayCollisionMesh", "Gets the collision information between a ray and a mesh."],
    ["GetRayCollisionTriangle", "Gets the collision information between a ray and a triangle."],
    ["GetRayCollisionQuad", "Gets the collision information between a ray and a quad."],
    // Input - new functions
    ["IsKeyPressed", "Checks if a specific key was pressed during the current frame.", "raylib.IsKeyPressed(${1:key})"],
    ["IsKeyPressedRepeat", "Checks if a key is being pressed with auto-repeat active.", "raylib.IsKeyPressedRepeat(${1:key})"],
    ["GetKeyPressed", "Gets the key pressed as an integer key code (0 if none)."],
    ["GetCharPressed", "Gets the last Unicode character pressed (0 if none)."],
    ["GetKeyName", "Gets the human-readable name of a key code.", "raylib.GetKeyName(${1:key})"],
    ["IsMouseButtonPressed", "Checks if a mouse button was pressed during the current frame.", "raylib.IsMouseButtonPressed(${1:button})"],
    ["IsMouseButtonReleased", "Checks if a mouse button was released during the current frame.", "raylib.IsMouseButtonReleased(${1:button})"],
    // Drawing - new functions
    ["DrawEllipseV", "Draws a color-filled ellipse at the specified position (Vector2).", "raylib.DrawEllipseV(${1:center}, ${2:radiusH}, ${3:radiusV}, ${4:color})"],
    ["DrawEllipseLinesV", "Draws the outline of an ellipse at the specified position (Vector2).", "raylib.DrawEllipseLinesV(${1:center}, ${2:radiusH}, ${3:radiusV}, ${4:color})"],
    ["DrawLineDashed", "Draws a dashed line between two points.", "raylib.DrawLineDashed(${1:startPos}, ${2:endPos}, ${3:dashSize}, ${4:spaceSize}, ${5:color})"],
    // File system - new functions
    ["MakeDirectory", "Creates a directory at the specified path. Returns 0 on success.", "raylib.MakeDirectory(${1:dirPath})"],
    ["IsFileNameValid", "Checks if a filename string is valid (no illegal characters).", "raylib.IsFileNameValid(${1:fileName})"],
    ["FileCopy", "Copies a file from srcPath to dstPath. Returns 0 on success.", "raylib.FileCopy(${1:srcPath}, ${2:dstPath})"],
    ["FileMove", "Moves a file from srcPath to dstPath. Returns 0 on success.", "raylib.FileMove(${1:srcPath}, ${2:dstPath})"],
    ["FileRemove", "Deletes the specified file. Returns 0 on success.", "raylib.FileRemove(${1:fileName})"],
    ["FileRename", "Renames a file. Returns 0 on success.", "raylib.FileRename(${1:fileName}, ${2:newName})"],
    ["FileTextFindIndex", "Returns the byte offset of the first occurrence of search string in the file.", "raylib.FileTextFindIndex(${1:fileName}, ${2:search})"],
    ["FileTextReplace", "Replaces all occurrences of search string with replacement in a file.", "raylib.FileTextReplace(${1:fileName}, ${2:search}, ${3:replacement})"],
    ["GetDirectoryFileCount", "Returns the number of files in the specified directory.", "raylib.GetDirectoryFileCount(${1:dirPath})"],
    ["GetDirectoryFileCountEx", "Returns the number of files in a directory with optional filter and subdirectory scan.", "raylib.GetDirectoryFileCountEx(${1:basePath}, ${2:filter}, ${3:scanSubdirs})"],
    // Hashing - new functions
    ["ComputeCRC32", "Computes the CRC32 checksum of binary data. Returns an integer.", "raylib.ComputeCRC32(${1:data})"],
    ["ComputeMD5", "Computes the MD5 hash of binary data. Returns a table of 4 unsigned integers.", "raylib.ComputeMD5(${1:data})"],
    ["ComputeSHA1", "Computes the SHA1 hash of binary data. Returns a table of 5 unsigned integers.", "raylib.ComputeSHA1(${1:data})"],
    ["ComputeSHA256", "Computes the SHA256 hash of binary data. Returns a table of 8 unsigned integers.", "raylib.ComputeSHA256(${1:data})"],
    // Text - new functions
    ["LoadTextLines", "Splits a multi-line string into a Lua table of individual lines.", "raylib.LoadTextLines(${1:text})"],
    ["GetTextBetween", "Extracts the substring found between two delimiter strings.", "raylib.GetTextBetween(${1:text}, ${2:begin}, ${3:end})"],
    ["TextRemoveSpaces", "Returns a copy of the string with all spaces removed.", "raylib.TextRemoveSpaces(${1:text})"],
    ["TextReplaceAlloc", "Replaces all occurrences of search with replacement. Returns a new string.", "raylib.TextReplaceAlloc(${1:text}, ${2:search}, ${3:replacement})"],
    ["TextReplaceBetween", "Replaces the content between two delimiter strings with a replacement.", "raylib.TextReplaceBetween(${1:text}, ${2:begin}, ${3:end}, ${4:replacement})"],
    ["TextReplaceBetweenAlloc", "Replaces content between delimiters; returns a newly allocated string.", "raylib.TextReplaceBetweenAlloc(${1:text}, ${2:begin}, ${3:end}, ${4:replacement})"],
    ["TextInsertAlloc", "Inserts a string at a position and returns a newly allocated result.", "raylib.TextInsertAlloc(${1:text}, ${2:insert}, ${3:position})"],
    ["MeasureTextCodepoints", "Measures the pixel size of text given as a codepoint table.", "raylib.MeasureTextCodepoints(${1:font}, ${2:codepoints}, ${3:fontSize}, ${4:spacing})"],
    // Models - new functions
    ["UpdateModelAnimationEx", "Updates a model by blending two animations together.", "raylib.UpdateModelAnimationEx(${1:model}, ${2:animA}, ${3:frameA}, ${4:animB}, ${5:frameB}, ${6:blend})"],
    // >>> AUTO-GENERATED (raylib 6.0 full coverage) — 142 functions added
    ["BeginBlendMode", "Begin blending mode (alpha, additive, multiplied, subtract, custom).", "raylib.BeginBlendMode(${1:mode})"],
    ["BeginMode2D", "Begin 2D mode with custom camera (2D).", "raylib.BeginMode2D(${1:camera})"],
    ["BeginMode3D", "Begin 3D mode with custom camera (3D).", "raylib.BeginMode3D(${1:camera})"],
    ["BeginScissorMode", "Begin scissor mode (define screen area for following drawing).", "raylib.BeginScissorMode(${1:x}, ${2:y}, ${3:width}, ${4:height})"],
    ["BeginShaderMode", "Begin custom shader drawing.", "raylib.BeginShaderMode(${1:shader})"],
    ["BeginTextureMode", "Begin drawing to render texture.", "raylib.BeginTextureMode(${1:target})"],
    ["BeginVrStereoMode", "Begin stereo rendering (requires VR simulator).", "raylib.BeginVrStereoMode(${1:config})"],
    ["ChangeDirectory", "Change working directory, return true on success.", "raylib.ChangeDirectory(${1:dirPath})"],
    ["CompressData", "Compresses a binary string with DEFLATE; returns the compressed string.", "raylib.CompressData(${1:data})"],
    ["CreateCamera3D", "Creates a 3D Camera userdata (position, target, up, fovy, projection) to pass to BeginMode3D / UpdateCamera.", "raylib.CreateCamera3D(${1:position}, ${2:target}, ${3:up}, ${4:fovy}, ${5:projection})"],
    ["DecodeDataBase64", "Decodes a Base64 string; returns the original binary string.", "raylib.DecodeDataBase64(${1:data})"],
    ["DecompressData", "Decompresses a DEFLATE binary string; returns the original string.", "raylib.DecompressData(${1:compData})"],
    ["DirectoryExists", "Check if a directory path exists.", "raylib.DirectoryExists(${1:dirPath})"],
    ["DrawMeshInstanced", "Draw multiple mesh instances with material and a Lua array of transform matrices.", "raylib.DrawMeshInstanced(${1:mesh}, ${2:material}, ${3:transforms})"],
    ["DrawModelWires", "Draw a model wires (with texture if set).", "raylib.DrawModelWires(${1:model}, ${2:position}, ${3:scale}, ${4:tint})"],
    ["DrawModelWiresEx", "Draw a model wires (with texture if set) with extended parameters.", "raylib.DrawModelWiresEx(${1:model}, ${2:position}, ${3:rotationAxis}, ${4:rotationAngle}, ${5:scale}, ${6:tint})"],
    ["DrawRectangleRoundedLines", "Draw rectangle lines with rounded edges.", "raylib.DrawRectangleRoundedLines(${1:rec}, ${2:roundness}, ${3:segments}, ${4:color})"],
    ["DrawRectangleRoundedLinesEx", "Draw rectangle with rounded edges outline.", "raylib.DrawRectangleRoundedLinesEx(${1:rec}, ${2:roundness}, ${3:segments}, ${4:lineThick}, ${5:color})"],
    ["DrawSphere", "Draw sphere.", "raylib.DrawSphere(${1:centerPos}, ${2:radius}, ${3:color})"],
    ["DrawSphereEx", "Draw sphere with extended parameters.", "raylib.DrawSphereEx(${1:centerPos}, ${2:radius}, ${3:rings}, ${4:slices}, ${5:color})"],
    ["DrawTriangleFan", "Draw a triangle fan from a Lua array of Vector2 points (first point is the center).", "raylib.DrawTriangleFan(${1:points}, ${2:color})"],
    ["EncodeDataBase64", "Encodes a binary string as Base64; returns the encoded string.", "raylib.EncodeDataBase64(${1:data})"],
    ["EndBlendMode", "End blending mode (reset to default: alpha blending)."],
    ["EndMode2D", "Ends 2D mode with custom camera."],
    ["EndMode3D", "Ends 3D mode and returns to default 2D orthographic mode."],
    ["EndScissorMode", "End scissor mode."],
    ["EndShaderMode", "End custom shader drawing (use default shader)."],
    ["EndTextureMode", "Ends drawing to render texture."],
    ["EndVrStereoMode", "End stereo rendering (requires VR simulator)."],
    ["ExportAutomationEventList", "Export automation events list as text file.", "raylib.ExportAutomationEventList(${1:list}, ${2:fileName})"],
    ["ExportDataAsCode", "Exports a binary string as a C byte-array source file. Returns true on success.", "raylib.ExportDataAsCode(${1:data}, ${2:fileName})"],
    ["FileExists", "Check if file exists.", "raylib.FileExists(${1:fileName})"],
    ["GenImageFontAtlas", "Generates a font atlas Image from a GlyphInfoArray; returns the image and a table of glyph rectangles.", "raylib.GenImageFontAtlas(${1:glyphs}, ${2:fontSize}, ${3:padding}, ${4:packMethod})"],
    ["GetApplicationDirectory", "Get the directory of the running application (uses static string)."],
    ["GetAutomationEventCount", "Returns the number of recorded events in an AutomationEventList.", "raylib.GetAutomationEventCount(${1:list})"],
    ["GetCameraMatrix", "Get camera transform matrix (view matrix).", "raylib.GetCameraMatrix(${1:camera})"],
    ["GetCameraMatrix2D", "Get camera 2d transform matrix.", "raylib.GetCameraMatrix2D(${1:camera})"],
    ["GetDirectoryPath", "Get full path for a given fileName with path (uses static string).", "raylib.GetDirectoryPath(${1:filePath})"],
    ["GetFileExtension", "Get pointer to extension for a filename string (includes dot: '.png').", "raylib.GetFileExtension(${1:fileName})"],
    ["GetFileLength", "Get file length in bytes (NOTE: GetFileSize() conflicts with windows.h).", "raylib.GetFileLength(${1:fileName})"],
    ["GetFileModTime", "Get file modification time (last write time).", "raylib.GetFileModTime(${1:fileName})"],
    ["GetFileName", "Get pointer to filename for a path string.", "raylib.GetFileName(${1:filePath})"],
    ["GetFileNameWithoutExt", "Get filename string without extension (uses static string).", "raylib.GetFileNameWithoutExt(${1:filePath})"],
    ["GetGamepadAxisCount", "Get axis count for a gamepad.", "raylib.GetGamepadAxisCount(${1:gamepad})"],
    ["GetGamepadAxisMovement", "Get movement value for a gamepad axis.", "raylib.GetGamepadAxisMovement(${1:gamepad}, ${2:axis})"],
    ["GetGamepadButtonPressed", "Get the last gamepad button pressed."],
    ["GetGamepadName", "Get gamepad internal name id.", "raylib.GetGamepadName(${1:gamepad})"],
    ["GetGestureDetected", "Get latest detected gesture."],
    ["GetGestureDragAngle", "Get gesture drag angle."],
    ["GetGestureDragVector", "Get gesture drag vector."],
    ["GetGestureHoldDuration", "Get gesture hold time in seconds."],
    ["GetGesturePinchAngle", "Get gesture pinch angle."],
    ["GetGesturePinchVector", "Get gesture pinch delta."],
    ["GetMouseDelta", "Get mouse delta between frames."],
    ["GetMouseWheelMoveV", "Get mouse wheel movement for both X and Y."],
    ["GetPrevDirectoryPath", "Get previous directory path for a given path (uses static string).", "raylib.GetPrevDirectoryPath(${1:dirPath})"],
    ["GetRenderHeight", "Get current render height (it considers HiDPI)."],
    ["GetRenderWidth", "Get current render width (it considers HiDPI)."],
    ["GetScreenToWorld2D", "Get the world space position for a 2d camera screen space position.", "raylib.GetScreenToWorld2D(${1:position}, ${2:camera})"],
    ["GetScreenToWorldRay", "Get a ray trace from screen position (i.e mouse).", "raylib.GetScreenToWorldRay(${1:position}, ${2:camera})"],
    ["GetScreenToWorldRayEx", "Get a ray trace from screen position (i.e mouse) in a viewport.", "raylib.GetScreenToWorldRayEx(${1:position}, ${2:camera}, ${3:width}, ${4:height})"],
    ["GetShaderLocation", "Get shader uniform location.", "raylib.GetShaderLocation(${1:shader}, ${2:uniformName})"],
    ["GetShaderLocationAttrib", "Get shader attribute location.", "raylib.GetShaderLocationAttrib(${1:shader}, ${2:attribName})"],
    ["GetTouchPointCount", "Get number of touch points."],
    ["GetTouchPointId", "Get touch point identifier for given index.", "raylib.GetTouchPointId(${1:index})"],
    ["GetTouchX", "Get touch position X for touch point 0 (relative to screen size)."],
    ["GetTouchY", "Get touch position Y for touch point 0 (relative to screen size)."],
    ["GetWindowPosition", "Get window position XY on monitor."],
    ["GetWorkingDirectory", "Get current working directory (uses static string)."],
    ["GetWorldToScreen", "Get the screen space position for a 3d world space position.", "raylib.GetWorldToScreen(${1:position}, ${2:camera})"],
    ["GetWorldToScreen2D", "Get the screen space position for a 2d camera world space position.", "raylib.GetWorldToScreen2D(${1:position}, ${2:camera})"],
    ["GetWorldToScreenEx", "Get size position for a 3d world space position.", "raylib.GetWorldToScreenEx(${1:position}, ${2:camera}, ${3:width}, ${4:height})"],
    ["IsFileDropped", "Check if a file has been dropped into window."],
    ["IsFileExtension", "Check file extension (recommended include point: .png, .wav).", "raylib.IsFileExtension(${1:fileName}, ${2:ext})"],
    ["IsGamepadAvailable", "Check if a gamepad is available.", "raylib.IsGamepadAvailable(${1:gamepad})"],
    ["IsGamepadButtonDown", "Check if a gamepad button is being pressed.", "raylib.IsGamepadButtonDown(${1:gamepad}, ${2:button})"],
    ["IsGamepadButtonPressed", "Check if a gamepad button has been pressed once.", "raylib.IsGamepadButtonPressed(${1:gamepad}, ${2:button})"],
    ["IsGamepadButtonReleased", "Check if a gamepad button has been released once.", "raylib.IsGamepadButtonReleased(${1:gamepad}, ${2:button})"],
    ["IsGamepadButtonUp", "Check if a gamepad button is NOT being pressed.", "raylib.IsGamepadButtonUp(${1:gamepad}, ${2:button})"],
    ["IsGestureDetected", "Check if a gesture have been detected.", "raylib.IsGestureDetected(${1:gesture})"],
    ["IsPathFile", "Check if a given path is a file or a directory.", "raylib.IsPathFile(${1:path})"],
    ["IsShaderValid", "Check if a shader is valid (loaded on GPU).", "raylib.IsShaderValid(${1:shader})"],
    ["LoadAutomationEventList", "Load automation events list from file, NULL for empty list, capacity = MAX_AUTOMATION_EVENTS.", "raylib.LoadAutomationEventList(${1:fileName})"],
    ["LoadDirectoryFiles", "Load directory filepaths, files and directories, no subdirs scan.", "raylib.LoadDirectoryFiles(${1:dirPath})"],
    ["LoadDirectoryFilesEx", "Load directory filepaths with extension filtering and subdir scan; some filters available: \"*.*\", \"FILES*\", \"DIRS*\".", "raylib.LoadDirectoryFilesEx(${1:basePath}, ${2:filter}, ${3:scanSubdirs})"],
    ["LoadDroppedFiles", "Returns a Lua array of file paths dropped onto the window this frame."],
    ["LoadFileData", "Loads a file's contents as a binary string.", "raylib.LoadFileData(${1:fileName})"],
    ["LoadFileText", "Loads a text file's contents as a string.", "raylib.LoadFileText(${1:fileName})"],
    ["LoadFontData", "Loads font glyph data; returns a GlyphInfoArray userdata for GenImageFontAtlas.", "raylib.LoadFontData(${1:fileData}, ${2:fontSize}, ${3:codepoints}, ${4:type})"],
    ["LoadMusicStreamFromMemory", "Load a music stream from an in-memory binary string (fileType e.g. \".ogg\").", "raylib.LoadMusicStreamFromMemory(${1:fileType}, ${2:data})"],
    ["LoadRandomSequence", "Load random values sequence, no values repeated.", "raylib.LoadRandomSequence(${1:count}, ${2:min}, ${3:max})"],
    ["LoadShader", "Load shader from files and bind default locations.", "raylib.LoadShader(${1:vsFileName}, ${2:fsFileName})"],
    ["LoadShaderFromMemory", "Load shader from code strings and bind default locations.", "raylib.LoadShaderFromMemory(${1:vsCode}, ${2:fsCode})"],
    ["LoadVrStereoConfig", "Load VR stereo config for VR simulator device parameters.", "raylib.LoadVrStereoConfig(${1:device})"],
    ["MemAlloc", "Allocates a raw memory block (returns a light-userdata pointer; advanced use).", "raylib.MemAlloc(${1:size})"],
    ["MemFree", "Frees a raw memory block previously allocated with MemAlloc.", "raylib.MemFree(${1:ptr})"],
    ["MemRealloc", "Reallocates a raw memory block (advanced use).", "raylib.MemRealloc(${1:ptr}, ${2:size})"],
    ["OpenURL", "Open URL with default system browser (if available).", "raylib.OpenURL(${1:url})"],
    ["PauseSound", "Pause a sound.", "raylib.PauseSound(${1:sound})"],
    ["PlayAutomationEvent", "Plays a recorded automation event from a list by index.", "raylib.PlayAutomationEvent(${1:list}, ${2:index})"],
    ["PollInputEvents", "Register all input events."],
    ["ResumeSound", "Resume a paused sound.", "raylib.ResumeSound(${1:sound})"],
    ["SaveFileData", "Writes a binary string to a file. Returns true on success.", "raylib.SaveFileData(${1:fileName}, ${2:data})"],
    ["SaveFileText", "Writes a string to a text file. Returns true on success.", "raylib.SaveFileText(${1:fileName}, ${2:text})"],
    ["SetAutomationEventBaseFrame", "Set automation event internal base frame to start recording.", "raylib.SetAutomationEventBaseFrame(${1:frame})"],
    ["SetAutomationEventList", "Sets the active AutomationEventList used for recording.", "raylib.SetAutomationEventList(${1:list})"],
    ["SetExitKey", "Set a custom key to exit program (default is ESC).", "raylib.SetExitKey(${1:key})"],
    ["SetGamepadMappings", "Set internal gamepad mappings (SDL_GameControllerDB).", "raylib.SetGamepadMappings(${1:mappings})"],
    ["SetGamepadVibration", "Set gamepad vibration for both motors (duration in seconds).", "raylib.SetGamepadVibration(${1:gamepad}, ${2:leftMotor}, ${3:rightMotor}, ${4:duration})"],
    ["SetGesturesEnabled", "Enable a set of gestures using flags.", "raylib.SetGesturesEnabled(${1:flags})"],
    ["SetLoadFileDataCallback", "Installs a Lua function to intercept binary file loads. Pass nil to restore the default.", "raylib.SetLoadFileDataCallback(${1:callback})"],
    ["SetLoadFileTextCallback", "Installs a Lua function to intercept text file loads. Pass nil to restore the default.", "raylib.SetLoadFileTextCallback(${1:callback})"],
    ["SetMouseCursor", "Set mouse cursor.", "raylib.SetMouseCursor(${1:cursor})"],
    ["SetRandomSeed", "Set the seed for the random number generator.", "raylib.SetRandomSeed(${1:seed})"],
    ["SetSaveFileDataCallback", "Installs a Lua function to intercept binary file saves. Pass nil to restore the default.", "raylib.SetSaveFileDataCallback(${1:callback})"],
    ["SetSaveFileTextCallback", "Installs a Lua function to intercept text file saves. Pass nil to restore the default.", "raylib.SetSaveFileTextCallback(${1:callback})"],
    ["SetShaderValue", "Set shader uniform value.", "raylib.SetShaderValue(${1:shader}, ${2:locIndex}, ${3:value}, ${4:uniformType})"],
    ["SetShaderValueMatrix", "Set shader uniform value (matrix 4x4).", "raylib.SetShaderValueMatrix(${1:shader}, ${2:locIndex}, ${3:mat})"],
    ["SetShaderValueTexture", "Set shader uniform value and bind the texture (sampler2d).", "raylib.SetShaderValueTexture(${1:shader}, ${2:locIndex}, ${3:texture})"],
    ["SetShaderValueV", "Set shader uniform value vector.", "raylib.SetShaderValueV(${1:shader}, ${2:locIndex}, ${3:value}, ${4:uniformType}, ${5:count})"],
    ["SetSoundPan", "Set pan for a sound (-1.0 left, 0.0 center, 1.0 right).", "raylib.SetSoundPan(${1:sound}, ${2:pan})"],
    ["SetSoundPitch", "Set pitch for a sound (1.0 is base level).", "raylib.SetSoundPitch(${1:sound}, ${2:pitch})"],
    ["SetTraceLogCallback", "Installs a Lua function as the trace-log callback. Pass nil to restore the default.", "raylib.SetTraceLogCallback(${1:callback})"],
    ["SetTraceLogLevel", "Set the current threshold (minimum) log level.", "raylib.SetTraceLogLevel(${1:logLevel})"],
    ["SetWindowIcons", "Set the window icons from a Lua array of Image userdata (RGBA 32bit).", "raylib.SetWindowIcons(${1:images})"],
    ["StartAutomationEventRecording", "Start recording automation events (AutomationEventList must be set)."],
    ["StopAutomationEventRecording", "Stop recording automation events."],
    ["SwapScreenBuffer", "Swap back buffer with front buffer (screen drawing)."],
    ["TraceLog", "Write a trace-log message at the given level (LOG_INFO, LOG_WARNING, LOG_ERROR, ...).", "raylib.TraceLog(${1:logLevel}, ${2:text})"],
    ["UnloadAutomationEventList", "Unload automation events list from file.", "raylib.UnloadAutomationEventList(${1:list})"],
    ["UnloadDirectoryFiles", "Unload filepaths.", "raylib.UnloadDirectoryFiles(${1:files})"],
    ["UnloadDroppedFiles", "No-op kept for API symmetry (LoadDroppedFiles already returns a Lua table)."],
    ["UnloadFileData", "Unload file data allocated by LoadFileData().", "raylib.UnloadFileData(${1:data})"],
    ["UnloadFileText", "Unload file text data allocated by LoadFileText().", "raylib.UnloadFileText(${1:text})"],
    ["UnloadFontData", "Frees a GlyphInfoArray returned by LoadFontData.", "raylib.UnloadFontData(${1:glyphs})"],
    ["UnloadRandomSequence", "Unload random values sequence.", "raylib.UnloadRandomSequence(${1:sequence})"],
    ["UnloadShader", "Unload shader from GPU memory (VRAM).", "raylib.UnloadShader(${1:shader})"],
    ["UnloadTextLines", "No-op kept for API symmetry (LoadTextLines already returns a Lua table).", "raylib.UnloadTextLines(${1:lines})"],
    ["UnloadVrStereoConfig", "Unload VR stereo config.", "raylib.UnloadVrStereoConfig(${1:config})"],
    ["UpdateCamera", "Update camera position for selected mode.", "raylib.UpdateCamera(${1:camera}, ${2:mode})"],
    ["UpdateCameraPro", "Update camera movement/rotation.", "raylib.UpdateCameraPro(${1:camera}, ${2:movement}, ${3:rotation}, ${4:zoom})"],
    ["WaitTime", "Wait for some time (halt program execution).", "raylib.WaitTime(${1:seconds})"],
    // <<< AUTO-GENERATED
  ];

  return fns.map(([name, detail, snippet]) => {
    const item = new vscode.CompletionItem(`${namespace}.${name}`, vscode.CompletionItemKind.Function);
    item.detail = detail;
    item.documentation = new vscode.MarkdownString(
      `**${namespace}.${name}()**\n\n${detail}\n\n**Usage Example:**\n\`\`\`lua\n${namespace}.${name}()\n\`\`\``
    );
    const resolvedSnippet = snippet
      ? snippet.replace(/^raylib\./, `${namespace}.`)
      : `${namespace}.${name}()`;
    item.insertText = new vscode.SnippetString(resolvedSnippet);
    return item;
  });
}
