type Entry = [name: string, detail: string, snippet?: string];

const fns: Entry[] = [
    ["SetShapesTexture", "Sets the texture to be used for shapes.", "raylib.SetShapesTexture(${1:texture}, ${2:rec})"],
    ["GetShapesTexture", "Gets the current texture used for shapes."],
    ["GetShapesTextureRectangle", "Gets the source rectangle of the current shapes texture."],
    ["DrawPixel", "Draws a pixel at the specified position with the specified color.", "raylib.DrawPixel(${1:posX}, ${2:posY}, ${3:color})"],
    ["DrawPixelV", "Draws a pixel at the specified position (Vector2) with the specified color.", "raylib.DrawPixelV(${1:position}, ${2:color})"],
    ["DrawLineV", "Draws a line between two points (Vector2).", "raylib.DrawLineV(${1:startPos}, ${2:endPos}, ${3:color})"],
    ["DrawCircleV", "Draws a circle at the specified position (Vector2) with the specified radius and color.", "raylib.DrawCircleV(${1:center}, ${2:radius}, ${3:color})"],
    ["DrawCircleLines", "Draws the outline of a circle at the specified position with the specified radius and color.", "raylib.DrawCircleLines(${1:centerX}, ${2:centerY}, ${3:radius}, ${4:color})"],
    ["DrawCircleLinesV", "Draws the outline of a circle at the specified position (Vector2) with the specified radius and color.", "raylib.DrawCircleLinesV(${1:center}, ${2:radius}, ${3:color})"],
    ["DrawEllipseLines", "Draws the outline of an ellipse at the specified position with the specified radii and color.", "raylib.DrawEllipseLines(${1:centerX}, ${2:centerY}, ${3:radiusH}, ${4:radiusV}, ${5:color})"],
    ["DrawRectangleV", "Draws a rectangle at the specified position (Vector2) with the specified width, height, and color.", "raylib.DrawRectangleV(${1:position}, ${2:size}, ${3:color})"],
    ["DrawRectangleRec", "Draws a rectangle using a Rectangle struct.", "raylib.DrawRectangleRec(${1:rec}, ${2:color})"],
    ["DrawRectanglePro", "Draws a rectangle with the specified position, size, and rotation.", "raylib.DrawRectanglePro(${1:rec}, ${2:origin}, ${3:rotation}, ${4:color})"],
    ["DrawRectangleGradientH", "Draws a rectangle with a horizontal gradient.", "raylib.DrawRectangleGradientH(${1:posX}, ${2:posY}, ${3:width}, ${4:height}, ${5:left}, ${6:right})"],
    ["DrawRectangleLinesEx", "Draws the outline of a rectangle with extended parameters.", "raylib.DrawRectangleLinesEx(${1:rec}, ${2:thick}, ${3:color})"],
    ["DrawSplineLinear", "Draws a linear spline.", "raylib.DrawSplineLinear(${1:points}, ${2:thick}, ${3:color})"],
    ["DrawSplineBasis", "Draws a basis spline.", "raylib.DrawSplineBasis(${1:points}, ${2:thick}, ${3:color})"],
    ["DrawSplineCatmullRom", "Draws a Catmull-Rom spline.", "raylib.DrawSplineCatmullRom(${1:points}, ${2:thick}, ${3:color})"],
    ["DrawSplineBezierQuadratic", "Draws a quadratic Bezier spline.", "raylib.DrawSplineBezierQuadratic(${1:points}, ${2:thick}, ${3:color})"],
    ["DrawSplineBezierCubic", "Draws a cubic Bezier spline.", "raylib.DrawSplineBezierCubic(${1:points}, ${2:thick}, ${3:color})"],
    ["DrawSplineSegmentLinear", "Draws a segment of a linear spline between two points.", "raylib.DrawSplineSegmentLinear(${1:p1}, ${2:p2}, ${3:thick}, ${4:color})"],
    ["DrawSplineSegmentBasis", "Draws a segment of a basis spline.", "raylib.DrawSplineSegmentBasis(${1:p1}, ${2:p2}, ${3:p3}, ${4:p4}, ${5:thick}, ${6:color})"],
    ["DrawSplineSegmentCatmullRom", "Draws a segment of a Catmull-Rom spline.", "raylib.DrawSplineSegmentCatmullRom(${1:p1}, ${2:p2}, ${3:p3}, ${4:p4}, ${5:thick}, ${6:color})"],
    ["DrawSplineSegmentBezierQuadratic", "Draws a segment of a quadratic Bezier spline.", "raylib.DrawSplineSegmentBezierQuadratic(${1:p1}, ${2:c2}, ${3:p3}, ${4:thick}, ${5:color})"],
    ["DrawSplineSegmentBezierCubic", "Draws a segment of a cubic Bezier spline.", "raylib.DrawSplineSegmentBezierCubic(${1:p1}, ${2:c2}, ${3:c3}, ${4:p4}, ${5:thick}, ${6:color})"],
    ["GetSplinePointLinear", "Gets a point on a linear spline.", "raylib.GetSplinePointLinear(${1:startPos}, ${2:endPos}, ${3:t})"],
    ["GetSplinePointBasis", "Gets a point on a basis spline.", "raylib.GetSplinePointBasis(${1:p1}, ${2:p2}, ${3:p3}, ${4:p4}, ${5:t})"],
    ["GetSplinePointCatmullRom", "Gets a point on a Catmull-Rom spline.", "raylib.GetSplinePointCatmullRom(${1:p1}, ${2:p2}, ${3:p3}, ${4:p4}, ${5:t})"],
    ["GetSplinePointBezierQuad", "Gets a point on a quadratic Bezier spline.", "raylib.GetSplinePointBezierQuad(${1:p1}, ${2:c2}, ${3:p3}, ${4:t})"],
    ["GetSplinePointBezierCubic", "Gets a point on a cubic Bezier spline.", "raylib.GetSplinePointBezierCubic(${1:p1}, ${2:c2}, ${3:c3}, ${4:p4}, ${5:t})"],
    ["CheckCollisionRecs", "Checks collision between two rectangles.", "raylib.CheckCollisionRecs(${1:rec1}, ${2:rec2})"],
    ["CheckCollisionCircles", "Checks collision between two circles.", "raylib.CheckCollisionCircles(${1:center1}, ${2:radius1}, ${3:center2}, ${4:radius2})"],
    ["CheckCollisionCircleRec", "Checks collision between a circle and a rectangle.", "raylib.CheckCollisionCircleRec(${1:center}, ${2:radius}, ${3:rec})"],
    ["CheckCollisionCircleLine", "Checks collision between a circle and a line.", "raylib.CheckCollisionCircleLine(${1:center}, ${2:radius}, ${3:p1}, ${4:p2})"],
    ["CheckCollisionPointRec", "Checks collision between a point and a rectangle.", "raylib.CheckCollisionPointRec(${1:point}, ${2:rec})"],
    ["CheckCollisionPointCircle", "Checks collision between a point and a circle.", "raylib.CheckCollisionPointCircle(${1:point}, ${2:center}, ${3:radius})"],
    ["CheckCollisionPointTriangle", "Checks collision between a point and a triangle.", "raylib.CheckCollisionPointTriangle(${1:point}, ${2:p1}, ${3:p2}, ${4:p3})"],
    ["CheckCollisionPointLine", "Checks collision between a point and a line.", "raylib.CheckCollisionPointLine(${1:point}, ${2:p1}, ${3:p2}, ${4:threshold})"],
    ["CheckCollisionPointPoly", "Checks collision between a point and a polygon.", "raylib.CheckCollisionPointPoly(${1:point}, ${2:points})"],
    ["CheckCollisionLines", "Checks collision between two lines.", "raylib.CheckCollisionLines(${1:startPos1}, ${2:endPos1}, ${3:startPos2}, ${4:endPos2})"],
    ["GetCollisionRec", "Gets the collision rectangle between two rectangles.", "raylib.GetCollisionRec(${1:rec1}, ${2:rec2})"],
    ["InitWindow", "Initializes a window with specified width, height, and title.", "raylib.InitWindow(${1:width}, ${2:height}, ${3:title})"],
    ["CloseWindow", "Closes the current window and releases all associated resources."],
    ["WindowShouldClose", "Checks if the window should close."],
    ["GetClipboardImage", "Retrieves an image from the system clipboard."],
    ["SetWindowIcon", "Sets the window icon using an image.", "raylib.SetWindowIcon(${1:image})"],
    ["TakeScreenshot", "Captures a screenshot of the current window.", "raylib.TakeScreenshot(${1:fileName})"],
    ["GetFPS", "Retrieves the current frames per second (FPS) of the application."],
    ["IsWindowMinimized", "Checks if the current window is minimized."],
    ["IsWindowMaximized", "Checks if the current window is maximized."],
    ["RestoreWindow", "Restores the window if it is minimized or maximized."],
    ["ToggleFullscreen", "Toggles fullscreen mode for the window."],
    ["SetClipboardText", "Sets the clipboard text to the specified value.", "raylib.SetClipboardText(${1:text})"],
    ["GetClipboardText", "Gets the text currently stored in the system clipboard."],
    ["GetMouseX", "Gets the X coordinate of the current mouse position."],
    ["GetMouseY", "Gets the Y coordinate of the current mouse position."],
    ["GetMousePosition", "Gets the current position of the mouse as a Vector2."],
    ["GetMouseWheelMove", "Gets the movement of the mouse wheel."],
    ["GetFrameTime", "Gets the frame time (time to process one frame) in seconds."],
    ["IsKeyReleased", "Checks if a specific key was released during the current frame.", "raylib.IsKeyReleased(${1:key})"],
    ["GetMonitorWidth", "Gets the width of the specified monitor.", "raylib.GetMonitorWidth(${1:monitor})"],
    ["GetMonitorHeight", "Gets the height of the specified monitor.", "raylib.GetMonitorHeight(${1:monitor})"],
    ["MaximizeWindow", "Maximizes the application window."],
    ["MinimizeWindow", "Minimizes the application window."],
    ["SetWindowTitle", "Sets the title of the application window.", "raylib.SetWindowTitle(${1:title})"],
    ["SetWindowPosition", "Sets the position of the application window.", "raylib.SetWindowPosition(${1:x}, ${2:y})"],
    ["SetWindowMonitor", "Sets the monitor on which the window is displayed.", "raylib.SetWindowMonitor(${1:monitor})"],
    ["SetWindowSize", "Sets the size of the application window.", "raylib.SetWindowSize(${1:width}, ${2:height})"],
    ["SetConfigFlags", "Sets configuration flags for the application window.", "raylib.SetConfigFlags(${1:flags})"],
    ["GetScreenWidth", "Gets the width of the screen."],
    ["GetScreenHeight", "Gets the height of the screen."],
    ["GetMonitorCount", "Gets the number of connected monitors."],
    ["GetMonitorName", "Gets the name of a specific monitor.", "raylib.GetMonitorName(${1:monitor})"],
    ["GetMonitorPhysicalWidth", "Gets the physical width of a specific monitor in millimeters.", "raylib.GetMonitorPhysicalWidth(${1:monitor})"],
    ["GetMonitorPhysicalHeight", "Gets the physical height of a specific monitor in millimeters.", "raylib.GetMonitorPhysicalHeight(${1:monitor})"],
    ["GetMonitorRefreshRate", "Gets the refresh rate of a specific monitor.", "raylib.GetMonitorRefreshRate(${1:monitor})"],
    ["GetMonitorPosition", "Gets the position of a specific monitor on the screen.", "raylib.GetMonitorPosition(${1:monitor})"],
    ["GetTime", "Gets the current time since the application started."],
    ["GetRandomValue", "Gets a random integer value between min and max (inclusive).", "raylib.GetRandomValue(${1:min}, ${2:max})"],
    ["SetTargetFPS", "Sets the target frames per second (FPS) for the application.", "raylib.SetTargetFPS(${1:fps})"],
    ["GetTargetFPS", "Gets the currently set target frames per second (FPS)."],
    ["IsKeyDown", "Checks if a specific key is currently being held down.", "raylib.IsKeyDown(${1:key})"],
    ["IsKeyUp", "Checks if a specific key is currently not being held down.", "raylib.IsKeyUp(${1:key})"],
    ["IsMouseButtonDown", "Checks if a specific mouse button is currently being held down.", "raylib.IsMouseButtonDown(${1:button})"],
    ["IsMouseButtonUp", "Checks if a specific mouse button is currently up (not pressed).", "raylib.IsMouseButtonUp(${1:button})"],
    ["SetMousePosition", "Sets the mouse position on the screen.", "raylib.SetMousePosition(${1:x}, ${2:y})"],
    ["SetMouseOffset", "Sets the mouse offset relative to the window.", "raylib.SetMouseOffset(${1:offsetX}, ${2:offsetY})"],
    ["SetMouseScale", "Sets the scale for mouse input.", "raylib.SetMouseScale(${1:scaleX}, ${2:scaleY})"],
    ["GetTouchPosition", "Gets the position of a touch input.", "raylib.GetTouchPosition(${1:index})"],
    ["ShowCursor", "Shows the mouse cursor on the screen."],
    ["HideCursor", "Hides the mouse cursor on the screen."],
    ["IsCursorHidden", "Checks if the cursor is currently hidden."],
    ["EnableCursor", "Enables the mouse cursor."],
    ["DisableCursor", "Disables the mouse cursor."],
    ["GetClipboardTextLength", "Gets the length of the clipboard text."],
    ["IsWindowReady", "Checks if the window is ready."],
    ["IsWindowFocused", "Checks if the window is currently focused."],
    ["IsWindowFullscreen", "Checks if the window is in fullscreen mode."],
    ["IsWindowHidden", "Checks if the window is currently hidden."],
    ["IsWindowResized", "Checks if the window has been resized."],
    ["IsWindowState", "Checks if the window has a specific state.", "raylib.IsWindowState(${1:flag})"],
    ["SetWindowState", "Sets a specific state for the window.", "raylib.SetWindowState(${1:flags})"],
    ["ClearWindowState", "Clears a specific state for the window.", "raylib.ClearWindowState(${1:flags})"],
    ["ToggleBorderlessWindowed", "Toggles borderless windowed mode."],
    ["SetWindowMinSize", "Sets the minimum size of the window.", "raylib.SetWindowMinSize(${1:width}, ${2:height})"],
    ["SetWindowMaxSize", "Sets the maximum size of the window.", "raylib.SetWindowMaxSize(${1:width}, ${2:height})"],
    ["SetWindowOpacity", "Sets the opacity of the window.", "raylib.SetWindowOpacity(${1:opacity})"],
    ["SetWindowFocused", "Sets the window as focused."],
    ["GetWindowHandle", "Gets the window handle."],
    ["GetCurrentMonitor", "Gets the current monitor."],
    ["GetWindowScaleDPI", "Gets the window's DPI scale."],
    ["EnableEventWaiting", "Enables event waiting."],
    ["DisableEventWaiting", "Disables event waiting."],
    ["IsCursorOnScreen", "Checks if the cursor is on the screen."],
    ["BeginDrawing", "Starts a new frame for drawing on the screen."],
    ["EndDrawing", "Ends the current frame and presents the drawn content to the screen."],
    ["ClearBackground", "Clears the entire screen with the specified color.", "raylib.ClearBackground(${1:color})"],
    ["DrawRectangle", "Draws a color-filled rectangle on the screen.", "raylib.DrawRectangle(${1:posX}, ${2:posY}, ${3:width}, ${4:height}, ${5:color})"],
    ["DrawCircle", "Draws a color-filled circle on the screen.", "raylib.DrawCircle(${1:centerX}, ${2:centerY}, ${3:radius}, ${4:color})"],
    ["DrawLineEx", "Draws a thick line with customizable start and end points.", "raylib.DrawLineEx(${1:startX}, ${2:startY}, ${3:endX}, ${4:endY}, ${5:thickness}, ${6:color})"],
    ["DrawEllipse", "Draws a color-filled ellipse on the screen.", "raylib.DrawEllipse(${1:centerX}, ${2:centerY}, ${3:radiusH}, ${4:radiusV}, ${5:color})"],
    ["DrawRectangleLines", "Draws the outline of a rectangle with specified parameters.", "raylib.DrawRectangleLines(${1:posX}, ${2:posY}, ${3:width}, ${4:height}, ${5:color})"],
    ["DrawRectangleGradient", "Draws a rectangle with a gradient fill.", "raylib.DrawRectangleGradient(${1:posX}, ${2:posY}, ${3:width}, ${4:height}, ${5:color1}, ${6:color2})"],
    ["DrawRectangleRounded", "Draws a rounded rectangle with specified parameters.", "raylib.DrawRectangleRounded(${1:posX}, ${2:posY}, ${3:width}, ${4:height}, ${5:roundness}, ${6:segments}, ${7:color})"],
    ["DrawLineStrip", "Draws a line strip with specified parameters.", "raylib.DrawLineStrip(${1:points}, ${2:color})"],
    ["DrawPoly", "Draws a polygon with specified parameters.", "raylib.DrawPoly(${1:center}, ${2:sides}, ${3:radius}, ${4:rotation}, ${5:color})"],
    ["DrawPolyLines", "Draws the outline of a polygon with specified parameters.", "raylib.DrawPolyLines(${1:center}, ${2:sides}, ${3:radius}, ${4:rotation}, ${5:color})"],
    ["DrawPolyLinesEx", "Draws the outline of a polygon with extended parameters.", "raylib.DrawPolyLinesEx(${1:center}, ${2:sides}, ${3:radius}, ${4:rotation}, ${5:thickness}, ${6:color})"],
    ["DrawCircleSector", "Draws a sector of a circle with specified parameters.", "raylib.DrawCircleSector(${1:center}, ${2:radius}, ${3:startAngle}, ${4:endAngle}, ${5:segments}, ${6:color})"],
    ["DrawCircleSectorLines", "Draws the outline of a sector of a circle with specified parameters.", "raylib.DrawCircleSectorLines(${1:center}, ${2:radius}, ${3:startAngle}, ${4:endAngle}, ${5:segments}, ${6:color})"],
    ["DrawRectangleGradientV", "Draws a rectangle with a vertical gradient fill.", "raylib.DrawRectangleGradientV(${1:posX}, ${2:posY}, ${3:width}, ${4:height}, ${5:top}, ${6:bottom})"],
    ["DrawRectangleGradientEx", "Draws a rectangle with an extended gradient fill.", "raylib.DrawRectangleGradientEx(${1:rec}, ${2:topLeft}, ${3:topRight}, ${4:bottomLeft}, ${5:bottomRight})"],
    ["DrawCircleGradient", "Draws a circle with a gradient fill.", "raylib.DrawCircleGradient(${1:centerX}, ${2:centerY}, ${3:radius}, ${4:innerColor}, ${5:outerColor})"],
    ["DrawLine", "Draws a line between two points.", "raylib.DrawLine(${1:startX}, ${2:startY}, ${3:endX}, ${4:endY}, ${5:color})"],
    ["DrawLineBezier", "Draws a Bezier line with specified parameters.", "raylib.DrawLineBezier(${1:startPos}, ${2:endPos}, ${3:thick}, ${4:color})"],
    ["DrawTriangle", "Draws a triangle with specified parameters.", "raylib.DrawTriangle(${1:v1}, ${2:v2}, ${3:v3}, ${4:color})"],
    ["DrawTriangleLines", "Draws the outline of a triangle with specified parameters.", "raylib.DrawTriangleLines(${1:v1}, ${2:v2}, ${3:v3}, ${4:color})"],
    ["DrawTriangleStrip", "Draws a strip of connected triangles using a list of vertices.", "raylib.DrawTriangleStrip(${1:points}, ${2:color})"],
    ["DrawRing", "Draws a ring with specified parameters.", "raylib.DrawRing(${1:center}, ${2:innerRadius}, ${3:outerRadius}, ${4:startAngle}, ${5:endAngle}, ${6:segments}, ${7:color})"],
    ["DrawRingLines", "Draws the outline of a ring with specified parameters.", "raylib.DrawRingLines(${1:center}, ${2:innerRadius}, ${3:outerRadius}, ${4:startAngle}, ${5:endAngle}, ${6:segments}, ${7:color})"],
    ["LoadSound", "Loads a sound from a file into memory.", "raylib.LoadSound(${1:fileName})"],
    ["PlaySound", "Plays a loaded sound.", "raylib.PlaySound(${1:sound})"],
    ["StopSound", "Stops a currently playing sound.", "raylib.StopSound(${1:sound})"],
    ["UnloadSound", "Unloads a loaded sound from memory.", "raylib.UnloadSound(${1:sound})"],
    ["LoadMusicStream", "Loads a music stream from a file into memory.", "raylib.LoadMusicStream(${1:fileName})"],
    ["PlayMusicStream", "Plays a loaded music stream.", "raylib.PlayMusicStream(${1:music})"],
    ["StopMusicStream", "Stops a currently playing music stream.", "raylib.StopMusicStream(${1:music})"],
    ["UpdateMusicStream", "Updates the buffers for a music stream.", "raylib.UpdateMusicStream(${1:music})"],
    ["SetMusicVolume", "Sets the volume for a music stream.", "raylib.SetMusicVolume(${1:music}, ${2:volume})"],
    ["SetSoundVolume", "Sets the volume for a sound.", "raylib.SetSoundVolume(${1:sound}, ${2:volume})"],
    ["IsSoundPlaying", "Checks if a sound is currently playing.", "raylib.IsSoundPlaying(${1:sound})"],
    ["InitAudioDevice", "Initializes the audio device."],
    ["CloseAudioDevice", "Closes the audio device."],
    ["IsAudioDeviceReady", "Checks if the audio device is ready."],
    ["SetMasterVolume", "Sets the master volume for all audio.", "raylib.SetMasterVolume(${1:volume})"],
    ["GetMasterVolume", "Gets the master volume for all audio."],
    ["IsWaveValid", "Checks if a wave is valid.", "raylib.IsWaveValid(${1:wave})"],
    ["LoadSoundFromWave", "Loads a sound from a wave.", "raylib.LoadSoundFromWave(${1:wave})"],
    ["LoadWave", "Loads a wave from a file.", "raylib.LoadWave(${1:fileName})"],
    ["LoadWaveFromMemory", "Loads a wave from memory.", "raylib.LoadWaveFromMemory(${1:fileType}, ${2:fileData}, ${3:dataSize})"],
    ["LoadSoundAlias", "Loads a sound alias.", "raylib.LoadSoundAlias(${1:alias}, ${2:fileName})"],
    ["IsSoundValid", "Checks if a sound is valid.", "raylib.IsSoundValid(${1:sound})"],
    ["UpdateSound", "Updates a sound buffer with new data.", "raylib.UpdateSound(${1:sound}, ${2:data}, ${3:dataSize})"],
    ["UnloadWave", "Unloads a wave from memory.", "raylib.UnloadWave(${1:wave})"],
    ["UnloadSoundAlias", "Unloads a sound alias from memory.", "raylib.UnloadSoundAlias(${1:alias})"],
    ["ExportWave", "Exports a wave to a file.", "raylib.ExportWave(${1:wave}, ${2:fileName})"],
    ["ExportWaveAsCode", "Exports a wave as C code.", "raylib.ExportWaveAsCode(${1:wave}, ${2:fileName})"],
    ["WaveCopy", "Copies a wave.", "raylib.WaveCopy(${1:wave})"],
    ["WaveCrop", "Crops a wave.", "raylib.WaveCrop(${1:wave}, ${2:initSample}, ${3:finalSample})"],
    ["WaveFormat", "Formats a wave.", "raylib.WaveFormat(${1:wave}, ${2:sampleRate}, ${3:sampleSize}, ${4:channels})"],
    ["LoadWaveSamples", "Loads wave samples.", "raylib.LoadWaveSamples(${1:wave})"],
    ["UnloadWaveSamples", "Unloads wave samples from memory.", "raylib.UnloadWaveSamples(${1:samples})"],
    ["IsMusicValid", "Checks if a music object is valid.", "raylib.IsMusicValid(${1:music})"],
    ["UnloadMusicStream", "Unloads a music stream from memory.", "raylib.UnloadMusicStream(${1:music})"],
    ["IsMusicStreamPlaying", "Checks if a music stream is currently playing.", "raylib.IsMusicStreamPlaying(${1:music})"],
    ["PauseMusicStream", "Pauses the currently playing music stream.", "raylib.PauseMusicStream(${1:music})"],
    ["ResumeMusicStream", "Resumes the paused music stream.", "raylib.ResumeMusicStream(${1:music})"],
    ["SeekMusicStream", "Seeks to a specific position in the music stream.", "raylib.SeekMusicStream(${1:music}, ${2:position})"],
    ["SetMusicPitch", "Sets the pitch for the music stream.", "raylib.SetMusicPitch(${1:music}, ${2:pitch})"],
    ["SetMusicPan", "Sets the pan for the music stream.", "raylib.SetMusicPan(${1:music}, ${2:pan})"],
    ["GetMusicTimeLength", "Gets the total length of the music stream.", "raylib.GetMusicTimeLength(${1:music})"],
    ["GetMusicTimePlayed", "Gets the total time played of the music stream.", "raylib.GetMusicTimePlayed(${1:music})"],
    ["LoadAudioStream", "Loads an audio stream with specified sample rate, sample size, and channel count.", "raylib.LoadAudioStream(${1:sampleRate}, ${2:sampleSize}, ${3:channels})"],
    ["IsAudioStreamValid", "Checks if an audio stream is valid.", "raylib.IsAudioStreamValid(${1:stream})"],
    ["UnloadAudioStream", "Unloads an audio stream from memory, freeing all associated resources.", "raylib.UnloadAudioStream(${1:stream})"],
    ["UpdateAudioStream", "Updates an audio stream with new audio data.", "raylib.UpdateAudioStream(${1:stream}, ${2:data}, ${3:frameCount})"],
    ["IsAudioStreamProcessed", "Checks if an audio stream is currently being processed.", "raylib.IsAudioStreamProcessed(${1:stream})"],
    ["PlayAudioStream", "Plays an audio stream, starting from the current buffer position.", "raylib.PlayAudioStream(${1:stream})"],
    ["PauseAudioStream", "Pauses the currently playing audio stream.", "raylib.PauseAudioStream(${1:stream})"],
    ["ResumeAudioStream", "Resumes a paused audio stream, continuing playback from its current position.", "raylib.ResumeAudioStream(${1:stream})"],
    ["IsAudioStreamPlaying", "Checks if an audio stream is currently playing.", "raylib.IsAudioStreamPlaying(${1:stream})"],
    ["StopAudioStream", "Stops the currently playing audio stream and resets its playback position.", "raylib.StopAudioStream(${1:stream})"],
    ["SetAudioStreamVolume", "Sets the volume for an audio stream.", "raylib.SetAudioStreamVolume(${1:stream}, ${2:volume})"],
    ["SetAudioStreamPitch", "Sets the pitch for an audio stream.", "raylib.SetAudioStreamPitch(${1:stream}, ${2:pitch})"],
    ["SetAudioStreamPan", "Sets the pan for an audio stream.", "raylib.SetAudioStreamPan(${1:stream}, ${2:pan})"],
    ["SetAudioStreamBufferSizeDefault", "Sets the default buffer size for an audio stream.", "raylib.SetAudioStreamBufferSizeDefault(${1:bufferSize})"],
    ["SetAudioStreamCallback", "Sets a callback function for an audio stream.", "raylib.SetAudioStreamCallback(${1:stream}, ${2:callback})"],
    ["AttachAudioStreamProcessor", "Attaches a processor to an audio stream.", "raylib.AttachAudioStreamProcessor(${1:stream}, ${2:processor})"],
    ["DetachAudioStreamProcessor", "Detaches a processor from an audio stream.", "raylib.DetachAudioStreamProcessor(${1:stream}, ${2:processor})"],
    ["AttachAudioMixedProcessor", "Attaches a processor to the mixed audio.", "raylib.AttachAudioMixedProcessor(${1:processor})"],
    ["DetachAudioMixedProcessor", "Detaches a processor from the mixed audio.", "raylib.DetachAudioMixedProcessor(${1:processor})"],
    ["GetFontDefault", "Gets the default font."],
    ["LoadFont", "Loads a font from a file.", "raylib.LoadFont(${1:fileName})"],
    ["LoadFontEx", "Loads a font from a file with extended parameters.", "raylib.LoadFontEx(${1:fileName}, ${2:fontSize}, ${3:codepoints})"],
    ["LoadFontFromImage", "Loads a font from an image.", "raylib.LoadFontFromImage(${1:image}, ${2:key}, ${3:firstChar})"],
    ["LoadFontFromMemory", "Loads a font from memory.", "raylib.LoadFontFromMemory(${1:fileType}, ${2:fileData}, ${3:fontSize}, ${4:codepoints})"],
    ["IsFontValid", "Checks if a font is valid.", "raylib.IsFontValid(${1:font})"],
    ["UnloadFont", "Unloads a font from memory.", "raylib.UnloadFont(${1:font})"],
    ["ExportFontAsCode", "Exports a font as C code.", "raylib.ExportFontAsCode(${1:font}, ${2:fileName})"],
    ["DrawFPS", "Draws the current FPS on the screen.", "raylib.DrawFPS(${1:posX}, ${2:posY})"],
    ["DrawText", "Draws text on the screen.", "raylib.DrawText(${1:text}, ${2:posX}, ${3:posY}, ${4:fontSize}, ${5:color})"],
    ["DrawTextEx", "Draws text on the screen with extended parameters.", "raylib.DrawTextEx(${1:font}, ${2:text}, ${3:position}, ${4:fontSize}, ${5:spacing}, ${6:tint})"],
    ["DrawTextPro", "Draws text on the screen with additional options.", "raylib.DrawTextPro(${1:font}, ${2:text}, ${3:position}, ${4:origin}, ${5:rotation}, ${6:fontSize}, ${7:spacing}, ${8:tint})"],
    ["DrawTextCodepoint", "Draws a single codepoint as text on the screen.", "raylib.DrawTextCodepoint(${1:font}, ${2:codepoint}, ${3:position}, ${4:fontSize}, ${5:tint})"],
    ["DrawTextCodepoints", "Draws multiple codepoints as text on the screen.", "raylib.DrawTextCodepoints(${1:font}, ${2:codepoints}, ${3:position}, ${4:fontSize}, ${5:spacing}, ${6:tint})"],
    ["SetTextLineSpacing", "Sets the line spacing for text.", "raylib.SetTextLineSpacing(${1:spacing})"],
    ["MeasureText", "Measures the width of the text.", "raylib.MeasureText(${1:text}, ${2:fontSize})"],
    ["MeasureTextEx", "Measures the size of the text with extended parameters.", "raylib.MeasureTextEx(${1:font}, ${2:text}, ${3:fontSize}, ${4:spacing})"],
    ["GetGlyphIndex", "Gets the index of a glyph in the font.", "raylib.GetGlyphIndex(${1:font}, ${2:codepoint})"],
    ["GetGlyphInfo", "Gets information about a glyph in the font.", "raylib.GetGlyphInfo(${1:font}, ${2:codepoint})"],
    ["GetGlyphAtlasRec", "Gets the atlas rectangle of a glyph in the font.", "raylib.GetGlyphAtlasRec(${1:font}, ${2:codepoint})"],
    ["LoadUTF8", "Loads a UTF-8 string.", "raylib.LoadUTF8(${1:codepoints})"],
    ["UnloadUTF8", "Unloads a UTF-8 string from memory.", "raylib.UnloadUTF8(${1:text})"],
    ["LoadCodepoints", "Loads codepoints from a UTF-8 string.", "raylib.LoadCodepoints(${1:text})"],
    ["UnloadCodepoints", "Unloads codepoints from memory.", "raylib.UnloadCodepoints(${1:codepoints})"],
    ["GetCodepointCount", "Gets the count of codepoints in a UTF-8 string.", "raylib.GetCodepointCount(${1:text})"],
    ["GetCodepoint", "Gets a codepoint from a UTF-8 string.", "raylib.GetCodepoint(${1:text})"],
    ["GetCodepointNext", "Gets the next codepoint in a UTF-8 string.", "raylib.GetCodepointNext(${1:text})"],
    ["GetCodepointPrevious", "Gets the previous codepoint in a UTF-8 string.", "raylib.GetCodepointPrevious(${1:text})"],
    ["CodepointToUTF8", "Converts a codepoint to a UTF-8 string.", "raylib.CodepointToUTF8(${1:codepoint})"],
    ["TextCopy", "Copies text from one string to another.", "raylib.TextCopy(${1:src})"],
    ["TextIsEqual", "Checks if two strings are equal.", "raylib.TextIsEqual(${1:text1}, ${2:text2})"],
    ["TextLength", "Gets the length of a text string.", "raylib.TextLength(${1:text})"],
    ["TextFormat", "Formats a text string.", "raylib.TextFormat(${1:text})"],
    ["TextSubtext", "Gets a subtext from a text string.", "raylib.TextSubtext(${1:text}, ${2:position}, ${3:length})"],
    ["TextReplace", "Replaces text in a string.", "raylib.TextReplace(${1:text}, ${2:search}, ${3:replacement})"],
    ["TextInsert", "Inserts text into a string.", "raylib.TextInsert(${1:text}, ${2:insert}, ${3:position})"],
    ["TextJoin", "Joins text strings.", "raylib.TextJoin(${1:textList}, ${2:delimiter})"],
    ["TextSplit", "Splits a text string.", "raylib.TextSplit(${1:text}, ${2:delimiter})"],
    ["TextAppend", "Appends text to a string.", "raylib.TextAppend(${1:text}, ${2:append}, ${3:position})"],
    ["TextFindIndex", "Finds the index of a substring in a text string.", "raylib.TextFindIndex(${1:text}, ${2:search})"],
    ["TextToUpper", "Converts a text string to uppercase.", "raylib.TextToUpper(${1:text})"],
    ["TextToLower", "Converts a text string to lowercase.", "raylib.TextToLower(${1:text})"],
    ["TextToPascal", "Converts a text string to Pascal case.", "raylib.TextToPascal(${1:text})"],
    ["TextToSnake", "Converts a text string to snake case.", "raylib.TextToSnake(${1:text})"],
    ["TextToCamel", "Converts a text string to camel case.", "raylib.TextToCamel(${1:text})"],
    ["TextToInteger", "Converts a text string to an integer.", "raylib.TextToInteger(${1:text})"],
    ["TextToFloat", "Converts a text string to a float.", "raylib.TextToFloat(${1:text})"],
    ["LoadImage", "Loads an image from a file.", "raylib.LoadImage(${1:fileName})"],
    ["UnloadImage", "Unloads an image from memory.", "raylib.UnloadImage(${1:image})"],
    ["LoadTexture", "Loads a texture from a file.", "raylib.LoadTexture(${1:fileName})"],
    ["LoadTextureFromImage", "Loads a texture from an existing image.", "raylib.LoadTextureFromImage(${1:image})"],
    ["UnloadTexture", "Unloads a texture from GPU memory.", "raylib.UnloadTexture(${1:texture})"],
    ["UpdateTexture", "Updates the contents of a texture with new data.", "raylib.UpdateTexture(${1:texture}, ${2:pixels})"],
    ["GenTextureMipmaps", "Generates mipmaps for a texture.", "raylib.GenTextureMipmaps(${1:texture})"],
    ["ImageResize", "Resizes an image to the specified dimensions.", "raylib.ImageResize(${1:image}, ${2:newWidth}, ${3:newHeight})"],
    ["ImageFlipHorizontal", "Flips an image horizontally.", "raylib.ImageFlipHorizontal(${1:image})"],
    ["ImageFlipVertical", "Flips an image vertically.", "raylib.ImageFlipVertical(${1:image})"],
    ["ImageCopy", "Creates a copy of an image.", "raylib.ImageCopy(${1:image})"],
    ["ImageCrop", "Crops an image to the specified rectangle.", "raylib.ImageCrop(${1:image}, ${2:x}, ${3:y}, ${4:width}, ${5:height})"],
    ["ImageColorTint", "Tints an image with a specified color.", "raylib.ImageColorTint(${1:image}, ${2:color})"],
    ["ImageColorInvert", "Inverts the colors of an image.", "raylib.ImageColorInvert(${1:image})"],
    ["ImageColorGrayscale", "Converts an image to grayscale.", "raylib.ImageColorGrayscale(${1:image})"],
    ["ImageColorBrightness", "Adjusts the brightness of an image.", "raylib.ImageColorBrightness(${1:image}, ${2:brightness})"],
    ["ImageColorContrast", "Adjusts the contrast of an image.", "raylib.ImageColorContrast(${1:image}, ${2:contrast})"],
    ["ImageColorReplace", "Replaces a color in an image with another color.", "raylib.ImageColorReplace(${1:image}, ${2:color}, ${3:replace})"],
    ["LoadTextureCubemap", "Loads a cubemap texture from an image.", "raylib.LoadTextureCubemap(${1:image}, ${2:layout})"],
    ["UpdateTextureRec", "Updates a specific region of a texture with new data.", "raylib.UpdateTextureRec(${1:texture}, ${2:x}, ${3:y}, ${4:width}, ${5:height}, ${6:pixels})"],
    ["LoadImageRaw", "Loads an image from raw pixel data.", "raylib.LoadImageRaw(${1:fileName}, ${2:width}, ${3:height}, ${4:format}, ${5:headerSize})"],
    ["LoadImageAnim", "Loads an animated image (GIF) from a file.", "raylib.LoadImageAnim(${1:fileName})"],
    ["LoadImageAnimFromMemory", "Loads an animated image (GIF) from memory.", "raylib.LoadImageAnimFromMemory(${1:fileType}, ${2:fileData}, ${3:dataSize})"],
    ["LoadImageFromMemory", "Loads an image from memory data.", "raylib.LoadImageFromMemory(${1:fileType}, ${2:fileData}, ${3:dataSize})"],
    ["LoadImageFromTexture", "Loads an image from a texture.", "raylib.LoadImageFromTexture(${1:texture})"],
    ["LoadImageFromScreen", "Loads an image from the current screen content."],
    ["IsImageValid", "Checks if an image is valid.", "raylib.IsImageValid(${1:image})"],
    ["ExportImage", "Exports an image to a file.", "raylib.ExportImage(${1:image}, ${2:fileName})"],
    ["ExportImageToMemory", "Exports an image to memory.", "raylib.ExportImageToMemory(${1:image}, ${2:fileType})"],
    ["ExportImageAsCode", "Exports an image as source code.", "raylib.ExportImageAsCode(${1:image}, ${2:fileName})"],
    ["GenImageColor", "Generates an image filled with a specific color.", "raylib.GenImageColor(${1:width}, ${2:height}, ${3:color})"],
    ["GenImageGradientLinear", "Generates a linear gradient image.", "raylib.GenImageGradientLinear(${1:width}, ${2:height}, ${3:direction}, ${4:start}, ${5:end})"],
    ["GenImageGradientRadial", "Generates a radial gradient image.", "raylib.GenImageGradientRadial(${1:width}, ${2:height}, ${3:density}, ${4:inner}, ${5:outer})"],
    ["GenImageGradientSquare", "Generates a square gradient image.", "raylib.GenImageGradientSquare(${1:width}, ${2:height}, ${3:density}, ${4:inner}, ${5:outer})"],
    ["GenImageChecked", "Generates an image with a checkered pattern.", "raylib.GenImageChecked(${1:width}, ${2:height}, ${3:checksX}, ${4:checksY}, ${5:col1}, ${6:col2})"],
    ["GenImageWhiteNoise", "Generates an image with white noise.", "raylib.GenImageWhiteNoise(${1:width}, ${2:height}, ${3:factor})"],
    ["GenImagePerlinNoise", "Generates an image with Perlin noise.", "raylib.GenImagePerlinNoise(${1:width}, ${2:height}, ${3:offsetX}, ${4:offsetY}, ${5:scale})"],
    ["GenImageCellular", "Generates an image with a cellular pattern.", "raylib.GenImageCellular(${1:width}, ${2:height}, ${3:tileSize})"],
    ["GenImageText", "Generates an image with text.", "raylib.GenImageText(${1:width}, ${2:height}, ${3:text})"],
    ["ImageFromImage", "Extracts a sub-image from an existing image.", "raylib.ImageFromImage(${1:image}, ${2:rec})"],
    ["ImageFromChannel", "Extracts a specific color channel from an image.", "raylib.ImageFromChannel(${1:image}, ${2:selectedChannel})"],
    ["ImageText", "Generates an image with a text string.", "raylib.ImageText(${1:text}, ${2:fontSize}, ${3:color})"],
    ["ImageTextEx", "Generates an image with extended text options.", "raylib.ImageTextEx(${1:font}, ${2:text}, ${3:fontSize}, ${4:spacing}, ${5:tint})"],
    ["ImageFormat", "Converts the format of an image.", "raylib.ImageFormat(${1:image}, ${2:newFormat})"],
    ["ImageToPOT", "Converts an image to power-of-two dimensions.", "raylib.ImageToPOT(${1:image}, ${2:fill})"],
    ["ImageAlphaCrop", "Crops the image by removing transparent pixels around it.", "raylib.ImageAlphaCrop(${1:image}, ${2:threshold})"],
    ["ImageAlphaClear", "Clears alpha values from an image.", "raylib.ImageAlphaClear(${1:image}, ${2:color}, ${3:threshold})"],
    ["ImageAlphaMask", "Applies an alpha mask to an image.", "raylib.ImageAlphaMask(${1:image}, ${2:alphaMask})"],
    ["ImageAlphaPremultiply", "Premultiplies the alpha channel of an image.", "raylib.ImageAlphaPremultiply(${1:image})"],
    ["ImageBlurGaussian", "Applies a Gaussian blur to an image.", "raylib.ImageBlurGaussian(${1:image}, ${2:blurSize})"],
    ["ImageKernelConvolution", "Applies a kernel convolution to an image.", "raylib.ImageKernelConvolution(${1:image}, ${2:kernel})"],
    ["ImageResizeNN", "Resizes an image using nearest-neighbor scaling.", "raylib.ImageResizeNN(${1:image}, ${2:newWidth}, ${3:newHeight})"],
    ["ImageResizeCanvas", "Resizes the image canvas while maintaining the image's position.", "raylib.ImageResizeCanvas(${1:image}, ${2:newWidth}, ${3:newHeight}, ${4:offsetX}, ${5:offsetY}, ${6:fill})"],
    ["ImageMipmaps", "Generates mipmaps for the image.", "raylib.ImageMipmaps(${1:image})"],
    ["ImageDither", "Applies a dithering effect to the image.", "raylib.ImageDither(${1:image}, ${2:rBpp}, ${3:gBpp}, ${4:bBpp}, ${5:aBpp})"],
    ["ImageRotate", "Rotates the image by a specified angle.", "raylib.ImageRotate(${1:image}, ${2:degrees})"],
    ["ImageRotateCW", "Rotates the image 90 degrees clockwise.", "raylib.ImageRotateCW(${1:image})"],
    ["ImageRotateCCW", "Rotates the image 90 degrees counterclockwise.", "raylib.ImageRotateCCW(${1:image})"],
    ["LoadImageColors", "Loads the color data from an image.", "raylib.LoadImageColors(${1:image})"],
    ["LoadImagePalette", "Loads the palette from an image.", "raylib.LoadImagePalette(${1:image}, ${2:maxPaletteSize})"],
    ["UnloadImageColors", "Unloads the color data from memory.", "raylib.UnloadImageColors(${1:colors})"],
    ["UnloadImagePalette", "Unloads the image palette from memory.", "raylib.UnloadImagePalette(${1:colors})"],
    ["GetImageAlphaBorder", "Gets the alpha border rectangle of an image.", "raylib.GetImageAlphaBorder(${1:image}, ${2:threshold})"],
    ["GetImageColor", "Gets the color of a specific pixel in an image.", "raylib.GetImageColor(${1:image}, ${2:x}, ${3:y})"],
    ["ImageClearBackground", "Clears the background of an image with a specified color.", "raylib.ImageClearBackground(${1:dst}, ${2:color})"],
    ["ImageDrawPixel", "Draws a pixel at the specified position in an image.", "raylib.ImageDrawPixel(${1:dst}, ${2:posX}, ${3:posY}, ${4:color})"],
    ["ImageDrawPixelV", "Draws a pixel at the specified position (Vector2) in an image.", "raylib.ImageDrawPixelV(${1:dst}, ${2:position}, ${3:color})"],
    ["ImageDrawLine", "Draws a line between two points in an image.", "raylib.ImageDrawLine(${1:dst}, ${2:startPosX}, ${3:startPosY}, ${4:endPosX}, ${5:endPosY}, ${6:color})"],
    ["ImageDrawLineV", "Draws a line between two points (Vector2) in an image.", "raylib.ImageDrawLineV(${1:dst}, ${2:start}, ${3:end}, ${4:color})"],
    ["ImageDrawLineEx", "Draws a line between two points with extended parameters in an image.", "raylib.ImageDrawLineEx(${1:dst}, ${2:start}, ${3:end}, ${4:thick}, ${5:color})"],
    ["ImageDrawCircle", "Draws a circle in an image at a specified position.", "raylib.ImageDrawCircle(${1:dst}, ${2:centerX}, ${3:centerY}, ${4:radius}, ${5:color})"],
    ["ImageDrawCircleV", "Draws a circle in an image at a specified position (Vector2).", "raylib.ImageDrawCircleV(${1:dst}, ${2:center}, ${3:radius}, ${4:color})"],
    ["ImageDrawCircleLines", "Draws the outline of a circle in an image at a specified position.", "raylib.ImageDrawCircleLines(${1:dst}, ${2:centerX}, ${3:centerY}, ${4:radius}, ${5:color})"],
    ["ImageDrawCircleLinesV", "Draws the outline of a circle in an image at a specified position (Vector2).", "raylib.ImageDrawCircleLinesV(${1:dst}, ${2:center}, ${3:radius}, ${4:color})"],
    ["ImageDrawRectangle", "Draws a rectangle in an image at a specified position.", "raylib.ImageDrawRectangle(${1:dst}, ${2:posX}, ${3:posY}, ${4:width}, ${5:height}, ${6:color})"],
    ["ImageDrawRectangleV", "Draws a rectangle in an image at a specified position (Vector2).", "raylib.ImageDrawRectangleV(${1:dst}, ${2:position}, ${3:size}, ${4:color})"],
    ["ImageDrawRectangleRec", "Draws a rectangle in an image using a Rectangle structure.", "raylib.ImageDrawRectangleRec(${1:dst}, ${2:rec}, ${3:color})"],
    ["ImageDrawRectangleLines", "Draws the outline of a rectangle in an image.", "raylib.ImageDrawRectangleLines(${1:dst}, ${2:rec}, ${3:thick}, ${4:color})"],
    ["ImageDrawTriangle", "Draws a triangle in an image using three points.", "raylib.ImageDrawTriangle(${1:dst}, ${2:v1}, ${3:v2}, ${4:v3}, ${5:color})"],
    ["ImageDrawTriangleEx", "Draws a triangle in an image using extended parameters.", "raylib.ImageDrawTriangleEx(${1:dst}, ${2:v1}, ${3:v2}, ${4:v3}, ${5:c1}, ${6:c2}, ${7:c3})"],
    ["ImageDrawTriangleLines", "Draws the outline of a triangle in an image.", "raylib.ImageDrawTriangleLines(${1:dst}, ${2:v1}, ${3:v2}, ${4:v3}, ${5:color})"],
    ["ImageDrawTriangleFan", "Draws a triangle fan in an image.", "raylib.ImageDrawTriangleFan(${1:dst}, ${2:points}, ${3:color})"],
    ["ImageDrawTriangleStrip", "Draws a triangle strip in an image.", "raylib.ImageDrawTriangleStrip(${1:dst}, ${2:points}, ${3:color})"],
    ["ImageDraw", "Draws an image onto another image.", "raylib.ImageDraw(${1:dst}, ${2:src}, ${3:srcRec}, ${4:dstRec}, ${5:tint})"],
    ["ImageDrawText", "Draws text on an image.", "raylib.ImageDrawText(${1:dst}, ${2:text}, ${3:posX}, ${4:posY}, ${5:fontSize}, ${6:color})"],
    ["ImageDrawTextEx", "Draws text on an image using extended parameters.", "raylib.ImageDrawTextEx(${1:dst}, ${2:font}, ${3:text}, ${4:position}, ${5:fontSize}, ${6:spacing}, ${7:tint})"],
    ["LoadRenderTexture", "Loads a render texture.", "raylib.LoadRenderTexture(${1:width}, ${2:height})"],
    ["IsTextureValid", "Checks if a texture is valid.", "raylib.IsTextureValid(${1:texture})"],
    ["IsRenderTextureValid", "Checks if a render texture is valid.", "raylib.IsRenderTextureValid(${1:target})"],
    ["UnloadRenderTexture", "Unloads a render texture from memory.", "raylib.UnloadRenderTexture(${1:target})"],
    ["SetTextureFilter", "Sets the filter mode for a texture.", "raylib.SetTextureFilter(${1:texture}, ${2:filter})"],
    ["SetTextureWrap", "Sets the wrap mode for a texture.", "raylib.SetTextureWrap(${1:texture}, ${2:wrap})"],
    ["DrawTexture", "Draws a texture at a specified position.", "raylib.DrawTexture(${1:texture}, ${2:posX}, ${3:posY}, ${4:tint})"],
    ["DrawTextureV", "Draws a texture at a specified position using a Vector2.", "raylib.DrawTextureV(${1:texture}, ${2:position}, ${3:tint})"],
    ["DrawTextureEx", "Draws a texture with extended parameters.", "raylib.DrawTextureEx(${1:texture}, ${2:position}, ${3:rotation}, ${4:scale}, ${5:tint})"],
    ["DrawTextureRec", "Draws a part of a texture.", "raylib.DrawTextureRec(${1:texture}, ${2:rec}, ${3:position}, ${4:tint})"],
    ["DrawTexturePro", "Draws a texture with extended parameters.", "raylib.DrawTexturePro(${1:texture}, ${2:srcrec}, ${3:dstrec}, ${4:origin}, ${5:rotation}, ${6:tint})"],
    ["DrawTextureNPatch", "Draws a texture using N-patch information.", "raylib.DrawTextureNPatch(${1:texture}, ${2:nPatchInfo}, ${3:dstrec}, ${4:origin}, ${5:rotation}, ${6:tint})"],
    ["ColorIsEqual", "Checks if two colors are equal.", "raylib.ColorIsEqual(${1:col1}, ${2:col2})"],
    ["Fade", "Applies fade effect to a color.", "raylib.Fade(${1:color}, ${2:alpha})"],
    ["ColorToInt", "Converts a Color to an integer representation.", "raylib.ColorToInt(${1:color})"],
    ["ColorNormalize", "Normalizes a Color to a Vector4.", "raylib.ColorNormalize(${1:color})"],
    ["ColorFromNormalized", "Converts a normalized Vector4 to a Color.", "raylib.ColorFromNormalized(${1:normalized})"],
    ["ColorToHSV", "Converts a Color to HSV.", "raylib.ColorToHSV(${1:color})"],
    ["ColorFromHSV", "Converts HSV (Hue, Saturation, Value) to a Color.", "raylib.ColorFromHSV(${1:hue}, ${2:saturation}, ${3:value})"],
    ["ColorTint", "Tints a Color with another Color.", "raylib.ColorTint(${1:color}, ${2:tint})"],
    ["ColorBrightness", "Adjusts the brightness of a Color.", "raylib.ColorBrightness(${1:color}, ${2:factor})"],
    ["ColorContrast", "Adjusts the contrast of a Color.", "raylib.ColorContrast(${1:color}, ${2:contrast})"],
    ["ColorAlpha", "Adjusts the alpha (transparency) of a Color.", "raylib.ColorAlpha(${1:color}, ${2:alpha})"],
    ["ColorAlphaBlend", "Blends two Colors based on alpha blending.", "raylib.ColorAlphaBlend(${1:dst}, ${2:src}, ${3:tint})"],
    ["ColorLerp", "Linearly interpolates between two Colors.", "raylib.ColorLerp(${1:color1}, ${2:color2}, ${3:factor})"],
    ["GetColor", "Gets the integer representation of a Color.", "raylib.GetColor(${1:hexValue})"],
    ["GetPixelColor", "Gets the color of a pixel from the screen at a given position.", "raylib.GetPixelColor(${1:srcPtr}, ${2:format})"],
    ["SetPixelColor", "Sets the color of a specific pixel on the screen or render target.", "raylib.SetPixelColor(${1:dstPtr}, ${2:color}, ${3:format})"],
    ["GetPixelDataSize", "Gets the size of the pixel data in memory for an image or texture.", "raylib.GetPixelDataSize(${1:width}, ${2:height}, ${3:format})"],
    ["LoadModel", "Loads a model from a file.", "raylib.LoadModel(${1:fileName})"],
    ["DrawModel", "Draws a model with default parameters.", "raylib.DrawModel(${1:model}, ${2:position}, ${3:scale}, ${4:tint})"],
    ["DrawModelEx", "Draws a model with extended parameters.", "raylib.DrawModelEx(${1:model}, ${2:position}, ${3:rotationAxis}, ${4:rotationAngle}, ${5:scale}, ${6:tint})"],
    ["UnloadModel", "Unloads a model from memory.", "raylib.UnloadModel(${1:model})"],
    ["UpdateModelAnimation", "Updates a model animation.", "raylib.UpdateModelAnimation(${1:model}, ${2:anim}, ${3:frame})"],
    ["DrawMesh", "Draws a mesh with default parameters.", "raylib.DrawMesh(${1:mesh}, ${2:material}, ${3:transform})"],
    ["UnloadMesh", "Unloads a mesh from memory.", "raylib.UnloadMesh(${1:mesh})"],
    ["GenMeshCube", "Generates a cube mesh.", "raylib.GenMeshCube(${1:width}, ${2:height}, ${3:length})"],
    ["GenMeshSphere", "Generates a sphere mesh.", "raylib.GenMeshSphere(${1:radius}, ${2:rings}, ${3:slices})"],
    ["GenMeshPlane", "Generates a plane mesh.", "raylib.GenMeshPlane(${1:width}, ${2:length}, ${3:resX}, ${4:resZ})"],
    ["DrawLine3D", "Draws a 3D line with specified parameters.", "raylib.DrawLine3D(${1:startPos}, ${2:endPos}, ${3:color})"],
    ["DrawPoint3D", "Draws a 3D point with specified parameters.", "raylib.DrawPoint3D(${1:position}, ${2:color})"],
    ["DrawCircle3D", "Draws a 3D circle with specified parameters.", "raylib.DrawCircle3D(${1:center}, ${2:radius}, ${3:rotationAxis}, ${4:rotationAngle}, ${5:color})"],
    ["DrawTriangle3D", "Draws a 3D triangle with specified parameters.", "raylib.DrawTriangle3D(${1:v1}, ${2:v2}, ${3:v3}, ${4:color})"],
    ["DrawTriangleStrip3D", "Draws a 3D triangle strip with specified parameters.", "raylib.DrawTriangleStrip3D(${1:points}, ${2:color})"],
    ["DrawCube", "Draws a 3D cube with specified parameters.", "raylib.DrawCube(${1:position}, ${2:width}, ${3:height}, ${4:length}, ${5:color})"],
    ["DrawCubeV", "Draws a 3D cube with specified parameters using a Vector3.", "raylib.DrawCubeV(${1:position}, ${2:size}, ${3:color})"],
    ["DrawCubeWires", "Draws the wireframe of a cube with specified parameters.", "raylib.DrawCubeWires(${1:position}, ${2:width}, ${3:height}, ${4:length}, ${5:color})"],
    ["DrawCubeWiresV", "Draws the wireframe of a cube with specified parameters using a Vector3.", "raylib.DrawCubeWiresV(${1:position}, ${2:size}, ${3:color})"],
    ["DrawSphereWires", "Draws the wireframe of a sphere with specified parameters.", "raylib.DrawSphereWires(${1:centerPos}, ${2:radius}, ${3:rings}, ${4:slices}, ${5:color})"],
    ["DrawCylinder", "Draws a cylinder with specified parameters.", "raylib.DrawCylinder(${1:position}, ${2:radiusTop}, ${3:radiusBottom}, ${4:height}, ${5:sides}, ${6:color})"],
    ["DrawCylinderEx", "Draws a cylinder with extended parameters.", "raylib.DrawCylinderEx(${1:startPos}, ${2:endPos}, ${3:startRadius}, ${4:endRadius}, ${5:sides}, ${6:color})"],
    ["DrawCylinderWires", "Draws the wireframe of a cylinder with specified parameters.", "raylib.DrawCylinderWires(${1:position}, ${2:radiusTop}, ${3:radiusBottom}, ${4:height}, ${5:sides}, ${6:color})"],
    ["DrawCylinderWiresEx", "Draws the wireframe of a cylinder with extended parameters.", "raylib.DrawCylinderWiresEx(${1:startPos}, ${2:endPos}, ${3:startRadius}, ${4:endRadius}, ${5:sides}, ${6:color})"],
    ["DrawCapsule", "Draws a capsule with specified parameters.", "raylib.DrawCapsule(${1:startPos}, ${2:endPos}, ${3:radius}, ${4:rings}, ${5:slices}, ${6:color})"],
    ["DrawCapsuleWires", "Draws the wireframe of a capsule with specified parameters.", "raylib.DrawCapsuleWires(${1:startPos}, ${2:endPos}, ${3:radius}, ${4:rings}, ${5:slices}, ${6:color})"],
    ["DrawPlane", "Draws a plane with specified parameters.", "raylib.DrawPlane(${1:centerPos}, ${2:size}, ${3:color})"],
    ["DrawRay", "Draws a ray with specified parameters.", "raylib.DrawRay(${1:ray}, ${2:color})"],
    ["DrawGrid", "Draws a grid with specified parameters.", "raylib.DrawGrid(${1:slices}, ${2:spacing})"],
    ["LoadModelFromMesh", "Loads a model from a mesh.", "raylib.LoadModelFromMesh(${1:mesh})"],
    ["IsModelValid", "Checks if a model is valid.", "raylib.IsModelValid(${1:model})"],
    ["GetModelBoundingBox", "Gets the bounding box of a model.", "raylib.GetModelBoundingBox(${1:model})"],
    ["DrawBoundingBox", "Draws a bounding box with specified parameters.", "raylib.DrawBoundingBox(${1:box}, ${2:color})"],
    ["DrawBillboard", "Draws a billboard with specified parameters.", "raylib.DrawBillboard(${1:camera}, ${2:texture}, ${3:position}, ${4:scale}, ${5:tint})"],
    ["DrawBillboardRec", "Draws a billboard with a specified rectangle.", "raylib.DrawBillboardRec(${1:camera}, ${2:texture}, ${3:rec}, ${4:position}, ${5:size}, ${6:tint})"],
    ["DrawBillboardPro", "Draws a billboard with extended parameters.", "raylib.DrawBillboardPro(${1:camera}, ${2:texture}, ${3:rec}, ${4:position}, ${5:up}, ${6:size}, ${7:origin}, ${8:rotation}, ${9:tint})"],
    ["UploadMesh", "Uploads a mesh to the GPU.", "raylib.UploadMesh(${1:mesh}, ${2:dynamic})"],
    ["UpdateMeshBuffer", "Updates a mesh buffer with new data.", "raylib.UpdateMeshBuffer(${1:mesh}, ${2:index}, ${3:data}, ${4:dataSize}, ${5:offset})"],
    ["GetMeshBoundingBox", "Gets the bounding box of a mesh.", "raylib.GetMeshBoundingBox(${1:mesh})"],
    ["GenMeshTangents", "Generates tangents for a mesh.", "raylib.GenMeshTangents(${1:mesh})"],
    ["ExportMesh", "Exports a mesh to a file.", "raylib.ExportMesh(${1:mesh}, ${2:fileName})"],
    ["ExportMeshAsCode", "Exports a mesh as C code.", "raylib.ExportMeshAsCode(${1:mesh}, ${2:fileName})"],
    ["GenMeshPoly", "Generates a polygon mesh.", "raylib.GenMeshPoly(${1:sides}, ${2:radius})"],
    ["GenMeshHemiSphere", "Generates a hemisphere mesh.", "raylib.GenMeshHemiSphere(${1:radius}, ${2:rings}, ${3:slices})"],
    ["GenMeshCylinder", "Generates a cylinder mesh.", "raylib.GenMeshCylinder(${1:radius}, ${2:height}, ${3:slices})"],
    ["GenMeshCone", "Generates a cone mesh.", "raylib.GenMeshCone(${1:radius}, ${2:height}, ${3:slices})"],
    ["GenMeshTorus", "Generates a torus mesh.", "raylib.GenMeshTorus(${1:radius}, ${2:size}, ${3:radSeg}, ${4:sides})"],
    ["GenMeshKnot", "Generates a knot mesh.", "raylib.GenMeshKnot(${1:radius}, ${2:size}, ${3:radSeg}, ${4:sides})"],
    ["GenMeshHeightmap", "Generates a heightmap mesh.", "raylib.GenMeshHeightmap(${1:heightmap}, ${2:size})"],
    ["GenMeshCubicmap", "Generates a cubicmap mesh.", "raylib.GenMeshCubicmap(${1:cubicmap}, ${2:cubeSize})"],
    ["LoadMaterials", "Loads materials from a file.", "raylib.LoadMaterials(${1:fileName})"],
    ["LoadMaterialDefault", "Loads the default material."],
    ["IsMaterialValid", "Checks if a material is valid.", "raylib.IsMaterialValid(${1:material})"],
    ["UnloadMaterial", "Unloads a material from memory.", "raylib.UnloadMaterial(${1:material})"],
    ["SetMaterialTexture", "Sets a texture for a material.", "raylib.SetMaterialTexture(${1:material}, ${2:mapType}, ${3:texture})"],
    ["SetModelMeshMaterial", "Sets the material for a model mesh.", "raylib.SetModelMeshMaterial(${1:model}, ${2:meshId}, ${3:materialId})"],
    ["LoadModelAnimations", "Loads model animations from a file.", "raylib.LoadModelAnimations(${1:fileName})"],
    ["UnloadModelAnimation", "Unloads a model animation from memory.", "raylib.UnloadModelAnimation(${1:animation})"],
    ["UnloadModelAnimations", "Unloads model animations from memory.", "raylib.UnloadModelAnimations(${1:animations})"],
    ["IsModelAnimationValid", "Checks if a model animation is valid.", "raylib.IsModelAnimationValid(${1:model}, ${2:anim})"],
    ["CheckCollisionSpheres", "Checks collision between two spheres.", "raylib.CheckCollisionSpheres(${1:center1}, ${2:radius1}, ${3:center2}, ${4:radius2})"],
    ["CheckCollisionBoxes", "Checks collision between two boxes.", "raylib.CheckCollisionBoxes(${1:box1}, ${2:box2})"],
    ["CheckCollisionBoxSphere", "Checks collision between a box and a sphere.", "raylib.CheckCollisionBoxSphere(${1:box}, ${2:center}, ${3:radius})"],
    ["GetRayCollisionSphere", "Gets the collision information between a ray and a sphere.", "raylib.GetRayCollisionSphere(${1:ray}, ${2:center}, ${3:radius})"],
    ["GetRayCollisionBox", "Gets the collision information between a ray and a box.", "raylib.GetRayCollisionBox(${1:ray}, ${2:box})"],
    ["GetRayCollisionMesh", "Gets the collision information between a ray and a mesh.", "raylib.GetRayCollisionMesh(${1:ray}, ${2:mesh}, ${3:transform})"],
    ["GetRayCollisionTriangle", "Gets the collision information between a ray and a triangle.", "raylib.GetRayCollisionTriangle(${1:ray}, ${2:p1}, ${3:p2}, ${4:p3})"],
    ["GetRayCollisionQuad", "Gets the collision information between a ray and a quad.", "raylib.GetRayCollisionQuad(${1:ray}, ${2:p1}, ${3:p2}, ${4:p3}, ${5:p4})"],
    // Input - new functions
    ["IsKeyPressed", "Checks if a specific key was pressed during the current frame.", "raylib.IsKeyPressed(${1:key})"],
    ["IsKeyPressedRepeat", "Checks if a key is being pressed with auto-repeat active.", "raylib.IsKeyPressedRepeat(${1:key})"],
    ["GetKeyPressed", "Gets the key pressed as an integer key code (0 if none)."],
    ["GetCharPressed", "Gets the last Unicode character pressed (0 if none)."],
    ["GetKeyName", "Gets the human-readable name of a key code.", "raylib.GetKeyName(${1:key})"],
    ["IsMouseButtonPressed", "Checks if a mouse button was pressed during the current frame.", "raylib.IsMouseButtonPressed(${1:button})"],
    ["IsMouseButtonReleased", "Checks if a mouse button was released during the current frame.", "raylib.IsMouseButtonReleased(${1:button})"],
    // Drawing - new functions
    ["DrawEllipseV", "Draws a color-filled ellipse at the specified position (Vector2).", "raylib.DrawEllipseV(${1:center}, ${2:radiusH}, ${3:radiusV}, ${4:color})"],
    ["DrawEllipseLinesV", "Draws the outline of an ellipse at the specified position (Vector2).", "raylib.DrawEllipseLinesV(${1:center}, ${2:radiusH}, ${3:radiusV}, ${4:color})"],
    ["DrawLineDashed", "Draws a dashed line between two points.", "raylib.DrawLineDashed(${1:startPos}, ${2:endPos}, ${3:dashSize}, ${4:spaceSize}, ${5:color})"],
    // File system - new functions
    ["MakeDirectory", "Creates a directory at the specified path. Returns 0 on success.", "raylib.MakeDirectory(${1:dirPath})"],
    ["IsFileNameValid", "Checks if a filename string is valid (no illegal characters).", "raylib.IsFileNameValid(${1:fileName})"],
    ["FileCopy", "Copies a file from srcPath to dstPath. Returns 0 on success.", "raylib.FileCopy(${1:srcPath}, ${2:dstPath})"],
    ["FileMove", "Moves a file from srcPath to dstPath. Returns 0 on success.", "raylib.FileMove(${1:srcPath}, ${2:dstPath})"],
    ["FileRemove", "Deletes the specified file. Returns 0 on success.", "raylib.FileRemove(${1:fileName})"],
    ["FileRename", "Renames a file. Returns 0 on success.", "raylib.FileRename(${1:fileName}, ${2:newName})"],
    ["FileTextFindIndex", "Returns the byte offset of the first occurrence of search string in the file.", "raylib.FileTextFindIndex(${1:fileName}, ${2:search})"],
    ["FileTextReplace", "Replaces all occurrences of search string with replacement in a file.", "raylib.FileTextReplace(${1:fileName}, ${2:search}, ${3:replacement})"],
    ["GetDirectoryFileCount", "Returns the number of files in the specified directory.", "raylib.GetDirectoryFileCount(${1:dirPath})"],
    ["GetDirectoryFileCountEx", "Returns the number of files in a directory with optional filter and subdirectory scan.", "raylib.GetDirectoryFileCountEx(${1:basePath}, ${2:filter}, ${3:scanSubdirs})"],
    // Hashing - new functions
    ["ComputeCRC32", "Computes the CRC32 checksum of binary data. Returns an integer.", "raylib.ComputeCRC32(${1:data})"],
    ["ComputeMD5", "Computes the MD5 hash of binary data. Returns a table of 4 unsigned integers.", "raylib.ComputeMD5(${1:data})"],
    ["ComputeSHA1", "Computes the SHA1 hash of binary data. Returns a table of 5 unsigned integers.", "raylib.ComputeSHA1(${1:data})"],
    ["ComputeSHA256", "Computes the SHA256 hash of binary data. Returns a table of 8 unsigned integers.", "raylib.ComputeSHA256(${1:data})"],
    // Text - new functions
    ["LoadTextLines", "Splits a multi-line string into a Lua table of individual lines.", "raylib.LoadTextLines(${1:text})"],
    ["GetTextBetween", "Extracts the substring found between two delimiter strings.", "raylib.GetTextBetween(${1:text}, ${2:begin}, ${3:end})"],
    ["TextRemoveSpaces", "Returns a copy of the string with all spaces removed.", "raylib.TextRemoveSpaces(${1:text})"],
    ["TextReplaceAlloc", "Replaces all occurrences of search with replacement. Returns a new string.", "raylib.TextReplaceAlloc(${1:text}, ${2:search}, ${3:replacement})"],
    ["TextReplaceBetween", "Replaces the content between two delimiter strings with a replacement.", "raylib.TextReplaceBetween(${1:text}, ${2:begin}, ${3:end}, ${4:replacement})"],
    ["TextReplaceBetweenAlloc", "Replaces content between delimiters; returns a newly allocated string.", "raylib.TextReplaceBetweenAlloc(${1:text}, ${2:begin}, ${3:end}, ${4:replacement})"],
    ["TextInsertAlloc", "Inserts a string at a position and returns a newly allocated result.", "raylib.TextInsertAlloc(${1:text}, ${2:insert}, ${3:position})"],
    ["MeasureTextCodepoints", "Measures the pixel size of text given as a codepoint table.", "raylib.MeasureTextCodepoints(${1:font}, ${2:codepoints}, ${3:fontSize}, ${4:spacing})"],
    // Models - new functions
    ["UpdateModelAnimationEx", "Updates a model by blending two animations together.", "raylib.UpdateModelAnimationEx(${1:model}, ${2:animA}, ${3:frameA}, ${4:animB}, ${5:frameB}, ${6:blend})"],
    // >>> AUTO-GENERATED (raylib 6.0 full coverage) — 142 functions added
    ["BeginBlendMode", "Begin blending mode (alpha, additive, multiplied, subtract, custom).", "raylib.BeginBlendMode(${1:mode})"],
    ["BeginMode2D", "Begin 2D mode with custom camera (2D).", "raylib.BeginMode2D(${1:camera})"],
    ["BeginMode3D", "Begin 3D mode with custom camera (3D).", "raylib.BeginMode3D(${1:camera})"],
    ["BeginScissorMode", "Begin scissor mode (define screen area for following drawing).", "raylib.BeginScissorMode(${1:x}, ${2:y}, ${3:width}, ${4:height})"],
    ["BeginShaderMode", "Begin custom shader drawing.", "raylib.BeginShaderMode(${1:shader})"],
    ["BeginTextureMode", "Begin drawing to render texture.", "raylib.BeginTextureMode(${1:target})"],
    ["BeginVrStereoMode", "Begin stereo rendering (requires VR simulator).", "raylib.BeginVrStereoMode(${1:config})"],
    ["ChangeDirectory", "Change working directory, return true on success.", "raylib.ChangeDirectory(${1:dirPath})"],
    ["CompressData", "Compresses a binary string with DEFLATE; returns the compressed string.", "raylib.CompressData(${1:data})"],
    ["CreateCamera3D", "Creates a 3D Camera userdata (position, target, up, fovy, projection) to pass to BeginMode3D / UpdateCamera.", "raylib.CreateCamera3D(${1:position}, ${2:target}, ${3:up}, ${4:fovy}, ${5:projection})"],
    ["DecodeDataBase64", "Decodes a Base64 string; returns the original binary string.", "raylib.DecodeDataBase64(${1:data})"],
    ["DecompressData", "Decompresses a DEFLATE binary string; returns the original string.", "raylib.DecompressData(${1:compData})"],
    ["DirectoryExists", "Check if a directory path exists.", "raylib.DirectoryExists(${1:dirPath})"],
    ["DrawMeshInstanced", "Draw multiple mesh instances with material and a Lua array of transform matrices.", "raylib.DrawMeshInstanced(${1:mesh}, ${2:material}, ${3:transforms})"],
    ["DrawModelWires", "Draw a model wires (with texture if set).", "raylib.DrawModelWires(${1:model}, ${2:position}, ${3:scale}, ${4:tint})"],
    ["DrawModelWiresEx", "Draw a model wires (with texture if set) with extended parameters.", "raylib.DrawModelWiresEx(${1:model}, ${2:position}, ${3:rotationAxis}, ${4:rotationAngle}, ${5:scale}, ${6:tint})"],
    ["DrawRectangleRoundedLines", "Draw rectangle lines with rounded edges.", "raylib.DrawRectangleRoundedLines(${1:rec}, ${2:roundness}, ${3:segments}, ${4:color})"],
    ["DrawRectangleRoundedLinesEx", "Draw rectangle with rounded edges outline.", "raylib.DrawRectangleRoundedLinesEx(${1:rec}, ${2:roundness}, ${3:segments}, ${4:lineThick}, ${5:color})"],
    ["DrawSphere", "Draw sphere.", "raylib.DrawSphere(${1:centerPos}, ${2:radius}, ${3:color})"],
    ["DrawSphereEx", "Draw sphere with extended parameters.", "raylib.DrawSphereEx(${1:centerPos}, ${2:radius}, ${3:rings}, ${4:slices}, ${5:color})"],
    ["DrawTriangleFan", "Draw a triangle fan from a Lua array of Vector2 points (first point is the center).", "raylib.DrawTriangleFan(${1:points}, ${2:color})"],
    ["EncodeDataBase64", "Encodes a binary string as Base64; returns the encoded string.", "raylib.EncodeDataBase64(${1:data})"],
    ["EndBlendMode", "End blending mode (reset to default: alpha blending)."],
    ["EndMode2D", "Ends 2D mode with custom camera."],
    ["EndMode3D", "Ends 3D mode and returns to default 2D orthographic mode."],
    ["EndScissorMode", "End scissor mode."],
    ["EndShaderMode", "End custom shader drawing (use default shader)."],
    ["EndTextureMode", "Ends drawing to render texture."],
    ["EndVrStereoMode", "End stereo rendering (requires VR simulator)."],
    ["ExportAutomationEventList", "Export automation events list as text file.", "raylib.ExportAutomationEventList(${1:list}, ${2:fileName})"],
    ["ExportDataAsCode", "Exports a binary string as a C byte-array source file. Returns true on success.", "raylib.ExportDataAsCode(${1:data}, ${2:fileName})"],
    ["FileExists", "Check if file exists.", "raylib.FileExists(${1:fileName})"],
    ["GenImageFontAtlas", "Generates a font atlas Image from a GlyphInfoArray; returns the image and a table of glyph rectangles.", "raylib.GenImageFontAtlas(${1:glyphs}, ${2:fontSize}, ${3:padding}, ${4:packMethod})"],
    ["GetApplicationDirectory", "Get the directory of the running application (uses static string)."],
    ["GetAutomationEventCount", "Returns the number of recorded events in an AutomationEventList.", "raylib.GetAutomationEventCount(${1:list})"],
    ["GetCameraMatrix", "Get camera transform matrix (view matrix).", "raylib.GetCameraMatrix(${1:camera})"],
    ["GetCameraMatrix2D", "Get camera 2d transform matrix.", "raylib.GetCameraMatrix2D(${1:camera})"],
    ["GetDirectoryPath", "Get full path for a given fileName with path (uses static string).", "raylib.GetDirectoryPath(${1:filePath})"],
    ["GetFileExtension", "Get pointer to extension for a filename string (includes dot: '.png').", "raylib.GetFileExtension(${1:fileName})"],
    ["GetFileLength", "Get file length in bytes (NOTE: GetFileSize() conflicts with windows.h).", "raylib.GetFileLength(${1:fileName})"],
    ["GetFileModTime", "Get file modification time (last write time).", "raylib.GetFileModTime(${1:fileName})"],
    ["GetFileName", "Get pointer to filename for a path string.", "raylib.GetFileName(${1:filePath})"],
    ["GetFileNameWithoutExt", "Get filename string without extension (uses static string).", "raylib.GetFileNameWithoutExt(${1:filePath})"],
    ["GetGamepadAxisCount", "Get axis count for a gamepad.", "raylib.GetGamepadAxisCount(${1:gamepad})"],
    ["GetGamepadAxisMovement", "Get movement value for a gamepad axis.", "raylib.GetGamepadAxisMovement(${1:gamepad}, ${2:axis})"],
    ["GetGamepadButtonPressed", "Get the last gamepad button pressed."],
    ["GetGamepadName", "Get gamepad internal name id.", "raylib.GetGamepadName(${1:gamepad})"],
    ["GetGestureDetected", "Get latest detected gesture."],
    ["GetGestureDragAngle", "Get gesture drag angle."],
    ["GetGestureDragVector", "Get gesture drag vector."],
    ["GetGestureHoldDuration", "Get gesture hold time in seconds."],
    ["GetGesturePinchAngle", "Get gesture pinch angle."],
    ["GetGesturePinchVector", "Get gesture pinch delta."],
    ["GetMouseDelta", "Get mouse delta between frames."],
    ["GetMouseWheelMoveV", "Get mouse wheel movement for both X and Y."],
    ["GetPrevDirectoryPath", "Get previous directory path for a given path (uses static string).", "raylib.GetPrevDirectoryPath(${1:dirPath})"],
    ["GetRenderHeight", "Get current render height (it considers HiDPI)."],
    ["GetRenderWidth", "Get current render width (it considers HiDPI)."],
    ["GetScreenToWorld2D", "Get the world space position for a 2d camera screen space position.", "raylib.GetScreenToWorld2D(${1:position}, ${2:camera})"],
    ["GetScreenToWorldRay", "Get a ray trace from screen position (i.e mouse).", "raylib.GetScreenToWorldRay(${1:position}, ${2:camera})"],
    ["GetScreenToWorldRayEx", "Get a ray trace from screen position (i.e mouse) in a viewport.", "raylib.GetScreenToWorldRayEx(${1:position}, ${2:camera}, ${3:width}, ${4:height})"],
    ["GetShaderLocation", "Get shader uniform location.", "raylib.GetShaderLocation(${1:shader}, ${2:uniformName})"],
    ["GetShaderLocationAttrib", "Get shader attribute location.", "raylib.GetShaderLocationAttrib(${1:shader}, ${2:attribName})"],
    ["GetTouchPointCount", "Get number of touch points."],
    ["GetTouchPointId", "Get touch point identifier for given index.", "raylib.GetTouchPointId(${1:index})"],
    ["GetTouchX", "Get touch position X for touch point 0 (relative to screen size)."],
    ["GetTouchY", "Get touch position Y for touch point 0 (relative to screen size)."],
    ["GetWindowPosition", "Get window position XY on monitor."],
    ["GetWorkingDirectory", "Get current working directory (uses static string)."],
    ["GetWorldToScreen", "Get the screen space position for a 3d world space position.", "raylib.GetWorldToScreen(${1:position}, ${2:camera})"],
    ["GetWorldToScreen2D", "Get the screen space position for a 2d camera world space position.", "raylib.GetWorldToScreen2D(${1:position}, ${2:camera})"],
    ["GetWorldToScreenEx", "Get size position for a 3d world space position.", "raylib.GetWorldToScreenEx(${1:position}, ${2:camera}, ${3:width}, ${4:height})"],
    ["IsFileDropped", "Check if a file has been dropped into window."],
    ["IsFileExtension", "Check file extension (recommended include point: .png, .wav).", "raylib.IsFileExtension(${1:fileName}, ${2:ext})"],
    ["IsGamepadAvailable", "Check if a gamepad is available.", "raylib.IsGamepadAvailable(${1:gamepad})"],
    ["IsGamepadButtonDown", "Check if a gamepad button is being pressed.", "raylib.IsGamepadButtonDown(${1:gamepad}, ${2:button})"],
    ["IsGamepadButtonPressed", "Check if a gamepad button has been pressed once.", "raylib.IsGamepadButtonPressed(${1:gamepad}, ${2:button})"],
    ["IsGamepadButtonReleased", "Check if a gamepad button has been released once.", "raylib.IsGamepadButtonReleased(${1:gamepad}, ${2:button})"],
    ["IsGamepadButtonUp", "Check if a gamepad button is NOT being pressed.", "raylib.IsGamepadButtonUp(${1:gamepad}, ${2:button})"],
    ["IsGestureDetected", "Check if a gesture have been detected.", "raylib.IsGestureDetected(${1:gesture})"],
    ["IsPathFile", "Check if a given path is a file or a directory.", "raylib.IsPathFile(${1:path})"],
    ["IsShaderValid", "Check if a shader is valid (loaded on GPU).", "raylib.IsShaderValid(${1:shader})"],
    ["LoadAutomationEventList", "Load automation events list from file, NULL for empty list, capacity = MAX_AUTOMATION_EVENTS.", "raylib.LoadAutomationEventList(${1:fileName})"],
    ["LoadDirectoryFiles", "Load directory filepaths, files and directories, no subdirs scan.", "raylib.LoadDirectoryFiles(${1:dirPath})"],
    ["LoadDirectoryFilesEx", "Load directory filepaths with extension filtering and subdir scan; some filters available: \"*.*\", \"FILES*\", \"DIRS*\".", "raylib.LoadDirectoryFilesEx(${1:basePath}, ${2:filter}, ${3:scanSubdirs})"],
    ["LoadDroppedFiles", "Returns a Lua array of file paths dropped onto the window this frame."],
    ["LoadFileData", "Loads a file's contents as a binary string.", "raylib.LoadFileData(${1:fileName})"],
    ["LoadFileText", "Loads a text file's contents as a string.", "raylib.LoadFileText(${1:fileName})"],
    ["LoadFontData", "Loads font glyph data; returns a GlyphInfoArray userdata for GenImageFontAtlas.", "raylib.LoadFontData(${1:fileData}, ${2:fontSize}, ${3:codepoints}, ${4:type})"],
    ["LoadMusicStreamFromMemory", "Load a music stream from an in-memory binary string (fileType e.g. \".ogg\").", "raylib.LoadMusicStreamFromMemory(${1:fileType}, ${2:data})"],
    ["LoadRandomSequence", "Load random values sequence, no values repeated.", "raylib.LoadRandomSequence(${1:count}, ${2:min}, ${3:max})"],
    ["LoadShader", "Load shader from files and bind default locations.", "raylib.LoadShader(${1:vsFileName}, ${2:fsFileName})"],
    ["LoadShaderFromMemory", "Load shader from code strings and bind default locations.", "raylib.LoadShaderFromMemory(${1:vsCode}, ${2:fsCode})"],
    ["LoadVrStereoConfig", "Load VR stereo config for VR simulator device parameters.", "raylib.LoadVrStereoConfig(${1:device})"],
    ["MemAlloc", "Allocates a raw memory block (returns a light-userdata pointer; advanced use).", "raylib.MemAlloc(${1:size})"],
    ["MemFree", "Frees a raw memory block previously allocated with MemAlloc.", "raylib.MemFree(${1:ptr})"],
    ["MemRealloc", "Reallocates a raw memory block (advanced use).", "raylib.MemRealloc(${1:ptr}, ${2:size})"],
    ["OpenURL", "Open URL with default system browser (if available).", "raylib.OpenURL(${1:url})"],
    ["PauseSound", "Pause a sound.", "raylib.PauseSound(${1:sound})"],
    ["PlayAutomationEvent", "Plays a recorded automation event from a list by index.", "raylib.PlayAutomationEvent(${1:list}, ${2:index})"],
    ["PollInputEvents", "Register all input events."],
    ["ResumeSound", "Resume a paused sound.", "raylib.ResumeSound(${1:sound})"],
    ["SaveFileData", "Writes a binary string to a file. Returns true on success.", "raylib.SaveFileData(${1:fileName}, ${2:data})"],
    ["SaveFileText", "Writes a string to a text file. Returns true on success.", "raylib.SaveFileText(${1:fileName}, ${2:text})"],
    ["SetAutomationEventBaseFrame", "Set automation event internal base frame to start recording.", "raylib.SetAutomationEventBaseFrame(${1:frame})"],
    ["SetAutomationEventList", "Sets the active AutomationEventList used for recording.", "raylib.SetAutomationEventList(${1:list})"],
    ["SetExitKey", "Set a custom key to exit program (default is ESC).", "raylib.SetExitKey(${1:key})"],
    ["SetGamepadMappings", "Set internal gamepad mappings (SDL_GameControllerDB).", "raylib.SetGamepadMappings(${1:mappings})"],
    ["SetGamepadVibration", "Set gamepad vibration for both motors (duration in seconds).", "raylib.SetGamepadVibration(${1:gamepad}, ${2:leftMotor}, ${3:rightMotor}, ${4:duration})"],
    ["SetGesturesEnabled", "Enable a set of gestures using flags.", "raylib.SetGesturesEnabled(${1:flags})"],
    ["SetLoadFileDataCallback", "Installs a Lua function to intercept binary file loads. Pass nil to restore the default.", "raylib.SetLoadFileDataCallback(${1:callback})"],
    ["SetLoadFileTextCallback", "Installs a Lua function to intercept text file loads. Pass nil to restore the default.", "raylib.SetLoadFileTextCallback(${1:callback})"],
    ["SetMouseCursor", "Set mouse cursor.", "raylib.SetMouseCursor(${1:cursor})"],
    ["SetRandomSeed", "Set the seed for the random number generator.", "raylib.SetRandomSeed(${1:seed})"],
    ["SetSaveFileDataCallback", "Installs a Lua function to intercept binary file saves. Pass nil to restore the default.", "raylib.SetSaveFileDataCallback(${1:callback})"],
    ["SetSaveFileTextCallback", "Installs a Lua function to intercept text file saves. Pass nil to restore the default.", "raylib.SetSaveFileTextCallback(${1:callback})"],
    ["SetShaderValue", "Set shader uniform value.", "raylib.SetShaderValue(${1:shader}, ${2:locIndex}, ${3:value}, ${4:uniformType})"],
    ["SetShaderValueMatrix", "Set shader uniform value (matrix 4x4).", "raylib.SetShaderValueMatrix(${1:shader}, ${2:locIndex}, ${3:mat})"],
    ["SetShaderValueTexture", "Set shader uniform value and bind the texture (sampler2d).", "raylib.SetShaderValueTexture(${1:shader}, ${2:locIndex}, ${3:texture})"],
    ["SetShaderValueV", "Set shader uniform value vector.", "raylib.SetShaderValueV(${1:shader}, ${2:locIndex}, ${3:value}, ${4:uniformType}, ${5:count})"],
    ["SetSoundPan", "Set pan for a sound (-1.0 left, 0.0 center, 1.0 right).", "raylib.SetSoundPan(${1:sound}, ${2:pan})"],
    ["SetSoundPitch", "Set pitch for a sound (1.0 is base level).", "raylib.SetSoundPitch(${1:sound}, ${2:pitch})"],
    ["SetTraceLogCallback", "Installs a Lua function as the trace-log callback. Pass nil to restore the default.", "raylib.SetTraceLogCallback(${1:callback})"],
    ["SetTraceLogLevel", "Set the current threshold (minimum) log level.", "raylib.SetTraceLogLevel(${1:logLevel})"],
    ["SetWindowIcons", "Set the window icons from a Lua array of Image userdata (RGBA 32bit).", "raylib.SetWindowIcons(${1:images})"],
    ["StartAutomationEventRecording", "Start recording automation events (AutomationEventList must be set)."],
    ["StopAutomationEventRecording", "Stop recording automation events."],
    ["SwapScreenBuffer", "Swap back buffer with front buffer (screen drawing)."],
    ["TraceLog", "Write a trace-log message at the given level (LOG_INFO, LOG_WARNING, LOG_ERROR, ...).", "raylib.TraceLog(${1:logLevel}, ${2:text})"],
    ["UnloadAutomationEventList", "Unload automation events list from file.", "raylib.UnloadAutomationEventList(${1:list})"],
    ["UnloadDirectoryFiles", "Unload filepaths.", "raylib.UnloadDirectoryFiles(${1:files})"],
    ["UnloadDroppedFiles", "No-op kept for API symmetry (LoadDroppedFiles already returns a Lua table)."],
    ["UnloadFileData", "Unload file data allocated by LoadFileData().", "raylib.UnloadFileData(${1:data})"],
    ["UnloadFileText", "Unload file text data allocated by LoadFileText().", "raylib.UnloadFileText(${1:text})"],
    ["UnloadFontData", "Frees a GlyphInfoArray returned by LoadFontData.", "raylib.UnloadFontData(${1:glyphs})"],
    ["UnloadRandomSequence", "Unload random values sequence.", "raylib.UnloadRandomSequence(${1:sequence})"],
    ["UnloadShader", "Unload shader from GPU memory (VRAM).", "raylib.UnloadShader(${1:shader})"],
    ["UnloadTextLines", "No-op kept for API symmetry (LoadTextLines already returns a Lua table).", "raylib.UnloadTextLines(${1:lines})"],
    ["UnloadVrStereoConfig", "Unload VR stereo config.", "raylib.UnloadVrStereoConfig(${1:config})"],
    ["UpdateCamera", "Update camera position for selected mode.", "raylib.UpdateCamera(${1:camera}, ${2:mode})"],
    ["UpdateCameraPro", "Update camera movement/rotation.", "raylib.UpdateCameraPro(${1:camera}, ${2:movement}, ${3:rotation}, ${4:zoom})"],
    ["WaitTime", "Wait for some time (halt program execution).", "raylib.WaitTime(${1:seconds})"],
    // <<< AUTO-GENERATED
];

/** A single raylib function resolved for the configured namespace. */
export interface RaylibFunction {
  /** Bare function name, e.g. `InitWindow`. */
  name: string;
  /** Namespace-qualified name, e.g. `raylib.InitWindow`. */
  qualified: string;
  /** Short one-line description. */
  detail: string;
  /** Ordered parameter names (empty for argument-less functions). */
  params: string[];
  /** Human-readable call signature, e.g. `raylib.InitWindow(width, height, title)`. */
  signature: string;
  /** Snippet string with tab stops, e.g. `raylib.InitWindow(${1:width}, ...)`. */
  snippet: string;
}

const TAB_STOP = /\$\{\d+:([^}]*)\}/g;

/**
 * Resolve the raw data array into structured, namespace-aware records. Shared by
 * the completion, hover, and signature-help providers so every surface stays in
 * sync with a single source of truth.
 */
export function getRaylibFunctions(namespace = "raylib"): RaylibFunction[] {
  return fns.map(([name, detail, snippet]) => {
    // Rewrite the hardcoded prefix in the data to the configured namespace.
    const resolvedSnippet = snippet
      ? snippet.replace(/^[A-Za-z_]\w*\./, `${namespace}.`)
      : `${namespace}.${name}()`;
    // Human-readable signature: strip tab-stop syntax (${1:width} -> width).
    const signature = resolvedSnippet.replace(TAB_STOP, "$1");
    const params = snippet ? [...snippet.matchAll(TAB_STOP)].map(m => m[1]) : [];
    return { name, qualified: `${namespace}.${name}`, detail, params, signature, snippet: resolvedSnippet };
  });
}

/** Build the shared MarkdownString shown in completion docs, hovers, and signature help. */
export function renderDocumentation(
  vscode: typeof import("vscode"),
  fn: RaylibFunction
): import("vscode").MarkdownString {
  const md = new vscode.MarkdownString(
    `${fn.detail}\n\n**Usage Example:**\n\`\`\`lua\n${fn.signature}\n\`\`\``
  );
  if (fn.params.length > 0) {
    md.appendMarkdown(`\n\n**Parameters:**\n${fn.params.map(p => `- \`${p}\``).join("\n")}`);
  }
  return md;
}

export function getCompletionItems(
  vscode: typeof import("vscode"),
  namespace = "raylib"
): import("vscode").CompletionItem[] {
  return getRaylibFunctions(namespace).map(fn => {
    const item = new vscode.CompletionItem(fn.qualified, vscode.CompletionItemKind.Function);
    item.detail = fn.detail;
    item.insertText = new vscode.SnippetString(fn.snippet);
    item.documentation = renderDocumentation(vscode, fn);
    return item;
  });
}
